### ISSUE TITLE
Refine vector wind data ingestion

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/eumetsat-EOWS#1]
Wind vector (metopb_scatterometerwind_ascat) data should have more info:

- [x] Is wind direction zero aligned with the North?
- [x] Is there any difference in nothern and souther emisphere data values?
- [ ] What are the visibility levels for different LOD ?
- [x] Is there a standard (or very common) colormap for wind speed hat we want to use?
- [x] What is the wind speed UOM?
- [x] Create a style with Wind Barbs #2 
- [x] (OPTIONAL) Optimize data as we load it in PostgreSQL to save space #9 
- [ ] Investigate adding a time column in the data or a separate polygon layer to show reference times for the data.

All this should be documented properly in the wiki and new issues might be create to link to this actions.

**Comment by Gnafu** [comment]
* 0° means from north to south, and increasing clockwise (WMO).
* Wind speed is provided in m/s.

**Comment by simboss** [comment]
- [ ] We need to go from narrow to sarrow 
- [ ] We might want to update the style so that we show m/s in the legend
