### ISSUE TITLE
Issue with reprojection to NPS

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/eumetsat-EOWS#10]
We have a problem when going from WGS84 to NPS.

I am pretty sure this depends on the data we have available in the WGS84 starting data but it is worth to check anyway. See attached images.

**MET9_RSS_IR039_PlateCarree in WGS84**
![wgs84](https://user-images.githubusercontent.com/693880/29980865-dd24ae68-8f4b-11e7-97fc-faaaff7156ca.jpg)

**MET9_RSS_IR039_PlateCarree in NPS**
![nps](https://user-images.githubusercontent.com/693880/29980877-e4d972c4-8f4b-11e7-8815-73a4a6307f54.jpg)

**Comment by aaime** [comment]
North Polar Stereographic is a bit vague, there are several of them. 
I've tried EPSG:32611 (UPS North):

![selezione_354](https://user-images.githubusercontent.com/325433/31008131-3ab0679e-a503-11e7-95fa-545b38f77327.png)

and EPSG:3411 (NSIDC Sea Ice Polar Stereographic North):

![selezione_355](https://user-images.githubusercontent.com/325433/31008157-54bad28c-a503-11e7-8029-4e5a447b5c81.png)

and also 3413, same result. So, which specific projection is the one above?

**Comment by simboss** [comment]
EPSG:3995 afair

**Comment by aaime** [comment]
This is what I get with 3995 on master... looks good:

![selezione_358](https://user-images.githubusercontent.com/325433/31023025-e19619b4-a53a-11e7-8a2c-f6591e136c07.png)
