### ISSUE TITLE
S-OSI GetFeatureInfo cannot be requested in JSON format

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/eumetsat-EOWS#113]
GetFeatureInfo requests in "application/json" format fail due to NaN values.

http://pf-docker.eoss-cloud.it/geoserver-master/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetFeatureInfo&FORMAT=image%2Fvnd.jpeg-png&TRANSPARENT=true&QUERY_LAYERS=eumetsat%3ASOSI&LAYERS=eumetsat%3ASOSI&STYLES=&tiled=true&TIME=2017-12-28T12%3A00%3A00.000Z&INFO_FORMAT=application%2Fjson&I=194&J=433&WIDTH=512&HEIGHT=512&CRS=EPSG%3A4326&BBOX=0%2C45%2C45%2C90

This is currently mitigated with a custom template for the text/html format

http://pf-docker.eoss-cloud.it/geoserver-master/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetFeatureInfo&FORMAT=image%2Fvnd.jpeg-png&TRANSPARENT=true&QUERY_LAYERS=eumetsat%3ASOSI&LAYERS=eumetsat%3ASOSI&STYLES=&tiled=true&TIME=2017-12-28T12%3A00%3A00.000Z&INFO_FORMAT=text%2Fhtml&I=194&J=433&WIDTH=512&HEIGHT=512&CRS=EPSG%3A4326&BBOX=0%2C45%2C45%2C90

The related GeoServer issue is : https://osgeo-org.atlassian.net/browse/GEOS-8569

**Comment by aaime** [comment]
I believe the equivalent GeoServer issue was https://osgeo-org.atlassian.net/browse/GEOS-8569, which has been solved during the last bug fix sprint.
Shall we close this ticket?
