### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by randomorder** [geosolutions-it/eumetsat-EOWS#114]
tentando di fare un download WPS del NETCDF:

/var/geoserver/datadir/tmp/filelocks/f8b1e01ed589c532fb30b9dcb5e590e6391c9370.lock (No space left on device)

**Comment by Gnafu** [comment]
I cleaned up the temporary upload folder the importer uses to store the shapefiles during an import. 
The WPS download is now working.
We should investigate why they where not cleaned up as we deployed a specific patch to prevent that.

**Comment by randomorder** [comment]
I collected some info that may be useful for debugging:
See datadir_listing_27_08_2018.tar.gz here: https://goo.gl/ELVAax

**Comment by Gnafu** [comment]
I found ICSI has the image 2.14.x-eows_importer_patch deployed, while it should have the **2.14.x-eows_imagemosaic_patch**

This is needed for the master instance only.

The 2.14.x-eows_importer_patch has a bug, fixed on a later commit: https://github.com/geoserver/geoserver/commit/177eea026bb7ee693081d414533751f7944a1e7b#diff-f5b59492e1e698f62e543309d8e50f4e

To prevent future disk space issues we should:

- Revert the deployed image to **2.14.x-eows_imagemosaic_patch**
- Enable the cron job to run remove_tmp_Rosa.sh in the /tmp/geoserver-datadir/uploads/ folder (/var/geoserver/datadir/uploads/ from the pods)

Another option is to:
- Update the GeoServer image with another patch, containing the [GEOS-8757 fix](https://github.com/geoserver/geoserver/commit/177eea026bb7ee693081d414533751f7944a1e7b#diff-f5b59492e1e698f62e543309d8e50f4e) 
- Deploy that on the master pod
- Disable the remove_tmp_Rosa.sh cleanup cron job
