### ISSUE TITLE
Preventive checks

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/eumetsat-EOWS#115]
Run trough the preventive checks every week

**Comment by simboss** [comment]
@Gnafu when is the next day to do that?

@fouad-semaan there is a doc to follow up

**Comment by Gnafu** [comment]
@simboss EUMETSAT is fixing a few issues that are preventing users to log in, we can start as the checks as soon as they are done.

@fouad-semaan I shared the doc with you

**Comment by fouad-semaan** [comment]
@Gnafu I put this under review. Just to remind you to review the updated doc.

**Comment by Gnafu** [comment]
@fouad-semaan the preventive checks are to be done every week. Can you please re-run the "WMS Application" section?

**Comment by fouad-semaan** [comment]
Sure. It will be done today.
