### ISSUE TITLE
Estimate new tasks

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/eumetsat-EOWS#118]
See taiga http://fstaiga.eoss-cloud.it/project/admin-pathfinder_wms/issue/481 and http://fstaiga.eoss-cloud.it/project/admin-pathfinder_wms/issue/483

**Comment by aaime** [comment]
For http://fstaiga.eoss-cloud.it/project/admin-pathfinder_wms/issue/481, the request is to allow download from WCS only certain layer(s). Two options:
* Use GeoFence (require for the undesired layers +WCS a role that nobody has)
* Use a custom security plugin that does the same, with its own little config
* Allow configuration of which protocols should publish the layer in the GeoServer config UI, e,g., in the existing WFS,WMS and WCS panels in the publishing tab, add a checkbox "publish using WxS". 

I guess the latter is the one that is the most interesting, but requires a mini-proposal, and it's not a small new feature (UI changes, config changes, new catalog filter) so we are good with running master? If so, I'd guess it can be done in 2-3 days of work.

**Comment by aaime** [comment]
For http://fstaiga.eoss-cloud.it/project/admin-pathfinder_wms/issue/483 the context of the ticket makes me believe the full resolution image downloads are done via the download process. 
The zip file name 
The bit creating the random file name is this one:
https://github.com/geoserver/geoserver/blob/2e3d10172e807539181ca552ead8adbfdac55be3/src/community/wps-
download/src/main/java/org/geoserver/wps/gs/download/RasterDownload.java#L811

The code could modified to use the layer name (is that matching the "product" being served?) or we could allow the caller to specify a name a desired filename

The output zip file name is probably in the same situation, but given it's the output of the process, there is other WPS machinery to look at.

Once we decide how we want to handle it (layer name, customizable name) I believe the work can be done in a couple of days max (hopefully just one, but I'm not so sure, as we'd have to handle potential file name conflicts among different processes, need to check if it can actually happen).

**Comment by simboss** [comment]
For the first one I would go with the possibility to enable/disable services at the layers level.
I would say 4 days.

For the second one, I would support both:

1.  By default the layername+curren time up to nanosecond (problem solved with clashes in real world and ability to version)
2. Ability to override the first part from the outside. I would still append the time to avoid clashes.

**Comment by aaime** [comment]
Yep, works for me. So it's 4 days for the service filtering by layer and 2 days for the download name fix.

**Comment by aaime** [comment]
Btw, this issue was about estimation, which happened, so, can we close it?
