### ISSUE TITLE
Investigate NetCDF serving requirements

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/eumetsat-EOWS#12]
We have a number of open points to investigate:

1. Support GHRSST standard info [here](https://www.ghrsst.org/)
2. Role of additional variable as suggested by Guillame
3. Question about creating a multivariable NetCDF in output. Apparently it should not be possible but what about the [OGC NetCDF Encoding Extension for WCS](http://docs.opengeospatial.org/is/14-100r2/14-100r2.html) 

Linked issues:

- [ ] #23

**Comment by dromagnoli** [comment]
about point 3, we should investigate on the possibility to get a NetCDF coverage through a getCoverage call containing all the variables

**Comment by simboss** [comment]
More on point 2 above.

We should get more NetCDF files from EUMETSAT and they are interesting in being able to use WCS as a refine download services.

The point is that aside main geophysical variables they will have other ancillary variables like quality flags, ice, land etc.. that we might have to output automagically as part of the NetCDF output.

I can also think about the case where we have variables like wind that usually comes in U,V splitted form but still once we do an export we should get them both together with the ancillary variables as said above.
