### ISSUE TITLE
Investigate randomly failing ascat imports

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/eumetsat-EOWS#129]
Noticed that the Many Ascat data is failing repeatedly and moved to Quarantine.
See email for attached log
 
Pls take a look in Quarantine directory as well

**Comment by Gnafu** [comment]
This just happened in DEV again.
It needs an investigation.

**Comment by simboss** [comment]
So, please prepare a case ready for investigation.

We need data. logs, etc.. as well as some sort posibility to replicate it.

**Comment by Gnafu** [comment]
All the failures observed during the last weeks of testing were due to a bad configuration of the ingestion service.
Blocking this until an actual random failure is observed.

**Comment by randomorder** [comment]
I am trying to find out where the quarantine directories are in order to close this

**Comment by randomorder** [comment]
All ingestions are reportedly ok (Fabrizio Borgia)
