### ISSUE TITLE
AbstractGTDataStoreGranuleCatalog has locks limiting scalability in face of index changes

### ISSUE THREAD

**Issue by aaime** [geosolutions-it/eumetsat-EOWS#133]
Most of the methods are guarded by a read/write lock that disallows concurrent writes (and concurrent read accesses while someone is writing on the catalog).
This implies that harvests, eventually concurrent ones, can lock up the mosaic until all writes are done.
The code in question is very old, we should check the SVN history to figure out why it's there.

**Comment by aaime** [comment]
Reference here: https://github.com/geotools/geotools/blob/149706fd5ae52fe69a463b7324105ed6c598e1d3/modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/catalog/AbstractGTDataStoreGranuleCatalog.java#L365

**Comment by aaime** [comment]
Searched in the history, goes back to GeoTools 8.x (around 2010) and it was apparently already there when the GT based catalogs for mosaic were created.

**Comment by simboss** [comment]
Understood, but do we need them?
If not let's try to remove them...

**Comment by simboss** [comment]
I think this can be close.

I remember we did some work back in January against this, right?

**Comment by aaime** [comment]
This one I believe: https://osgeo-org.atlassian.net/browse/GEOT-6199

**Comment by simboss** [comment]
Is this avail in 2.15?

Is there anything left to do?

I would want to close this one otherwise.

**Comment by aaime** [comment]
The work is old enough that it landed in 2.14.x too
