### ISSUE TITLE
GeoServer can't use geometry with functions in SLD

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/eumetsat-EOWS#14]
Due to [GEOT-4750](https://osgeo-org.atlassian.net/browse/GEOT-4750) we cannot get correct coordinates values of the features.

This affects the "emisphere" flag to draw the windbarbs.

For example the following:

><ogc:Function name="getY">  
>\<ogc:PropertyName\>geom</ogc:PropertyName>  
></ogc:Function>

Returns the actual pixel Y of the resulting image instead of the feature latitude.

**Comment by simboss** [comment]
Mapped to a task in Sprint 1

**Comment by aaime** [comment]
Fixed on 18.x and 17.x

**Comment by aaime** [comment]
Note, the changes actually caused a build failure on 17.x and have been reverted. However I don't think we actually need this fix on the GeoServer 2.11.x series no?

**Comment by Gnafu** [comment]
Verified working on both demo and production server.

**Comment by simboss** [comment]
@aaime I don't think we need to go back to 2.11
