### ISSUE TITLE
Bad rendering of 3995 SOSI layer

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/eumetsat-EOWS#141]
Some tiles of the SOSI layer are showing up semi-circle lines at low zoom levels.
The issue appears when re-projecting to EPSG:3995 (north polar).

Zooming in, the tiles are correct.

To be reproduced in local environment.

![Annotazione 2020-03-23 125131.png](https://images.zenhubusercontent.com/5cd44174fe59e12f2130c49d/417d515f-60bf-4e6b-be81-722ba1171951)

**Comment by Gnafu** [comment]
Similar issue found with 3857 reprojection

**Comment by Gnafu** [comment]
It is something related to the Jiffle script for the rendering transformation.
Removing that, it renders correctly.

JIRA here: https://osgeo-org.atlassian.net/browse/GEOS-9551

**Comment by simboss** [comment]
@aaime please, backport as back as possible.

We also need to cherrypick the fix to the EUM GS rabch (which is 2.16).

**Comment by aaime** [comment]
@Gnafu should be fixed, pushed the change to the EOWS branch

**Comment by Gnafu** [comment]
Assigning to me to deploy the code on CGI Gitlab

**Comment by Gnafu** [comment]
Confirmed working on "geoserver-dev"
