### ISSUE TITLE
Computing statistics on the fly in a defined AOI

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/eumetsat-EOWS#144]
**REQ WMS-PLP-GUI-1311**
*The user shall be able to compute statistics (mean, max, min, standard deviation values) in a defined area (AOI) for applicable products.*

This is a requirement that comes from the GUI since apparently the use should be able to requests stats on a certain area for the products and show them in the GUI.

I believe we can reuse/improve what we have for WPS processes and have CGI work on the client.
We need to put particular care on making sure we block requests that are too big and we requests that take too much time.

There is obviously configuration work to be done on the cluster as we need to make sure we have status sharing for WPS installed and enabled, control flow configured and the like.

This is created as an epic as it captures a User Story but need to be groomed.
We have top 10 days for this work.

**Comment by simboss** [comment]
Information sent to CGI, let's move this to review since we are waiting on feedback from them.

**Comment by randomorder** [comment]
can we close this one?
