### ISSUE TITLE
Ability to filter with something like an IN clause in SLD

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/eumetsat-EOWS#15]
We have style for arrows taken from wind data.

We have an attribute called LOD that says on each point at which scale we should show that arrow; the LOD goes top to bottom from 0 to N and is additive: we show 0 then 0+1 then 0+1+2 and so on.

Right now we are doing multiple OR but it would be good to use a IN that is optimized in databases as well.

**Comment by aaime** [comment]
There is a "in" function that can be used today to get part of the desired behavior, but it would not be encoded in SQL, it would be run in memory instead (the sql encoder, generally speaking, is not function aware). The filter would look something like this (untested, just to give you and idea):

````
<Filter>
   <PropertyIsEqualTo>
        <Function name="in">
             <PropertyName>theAttribute</PropertyName>
             <Literal>0</Literal>
             <Literal>1</Literal>
             <Literal>2</Literal>
        </Function>
        <Literal>true</Literal>
   </PropertyisEquasTo>
</Filter>
````

However, for cases like this one, why not use a simpler PropertyIsBetween instead?

````
<Filter>
   <PropertyIsBetween>
         <PropertyName>theAttribute</PropertyName>
         <Literal>0</Literal>
         <Literal>2</Literal>
   </PropertyisBetween>
</Filter>
````

**Comment by aaime** [comment]
In any case, I would estimate a fix for having the "in" function encoded in SQL to be 2 points

**Comment by simboss** [comment]
@Gnafu you might want to use the suggestion andrea gave us.

**Comment by simboss** [comment]
@Gnafu notice that Andrea is suggesting to **NOT** use the IN function at the moment but either the multiple OR approach or the PropertyIsBetween approach.

**Comment by Gnafu** [comment]
Done.
I used PropertyIsBetween

```
<ogc:PropertyIsBetween>
    <ogc:PropertyName>lod</ogc:PropertyName>
    <ogc:LowerBoundary>
        <ogc:Literal>0</ogc:Literal>
    </ogc:LowerBoundary>
    <ogc:UpperBoundary>
        <ogc:Literal>1</ogc:Literal>
    </ogc:UpperBoundary>
</ogc:PropertyIsBetween>
```

**Comment by simboss** [comment]
Created a task in TAIGA.

**Comment by aaime** [comment]
Fixed on master. As a new feature it has not been backported.
