### ISSUE TITLE
Fill in the Service ‘Title’ and ‘Abstract’ fields in the WMS/WCS/WFS GetCapabilites

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/eumetsat-EOWS#152]
This is   manual work to be done in cooperation with EUMETSAT as I believe they will  want to provide the title and abstract to use

**Comment by Gnafu** [comment]
Part of WMS-PLP-API-1920.
Currently blocked due to lack of access to PROD/DEV

**Comment by Gnafu** [comment]
Title and Abstract updated in DEV.
We need to know the exact text that EUMETSAT wants to be used

**Comment by Gnafu** [comment]
- Backup
- Copy from Product Navigator the layers' titles

**Comment by Gnafu** [comment]
TODO: 
- [ ] Review Elena list
- [ ] Notify client
