### ISSUE TITLE
Change the wording ‘Boring default style’ in the Styles

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/eumetsat-EOWS#153]
This is to change the description of the default styles in GeoServer like **raster**, **point**, **polygon** and so on because they contain the word boring. While we can remove this manually from the installation this description is hardcoded inside GeoServer codes to re-create the styles in case someone deletes them, hence we need to fix this in the code. I would simply go ahead and remove the word "boring" from everywhere.

This requires us to contact the community first and then doing the coding; it might need a GSIP? I don't think so but I would ask.

We needto backport this to 2.16 and to the 2-16 EUMETSAT branch we own (ask @Gnafu for pointers).

@Gnafu  as this will require a little bureaucracy and discussions, however we can start by fixing this in **their** styles right away.

**Comment by Gnafu** [comment]
Part of WMS-PLP-API-1920.
Currently blocked due to lack of access to PROD/DEV

**Comment by aaime** [comment]
Talked with @imranrajjad , a few pointers:

- Replace boring with "simple" or some such, and be descriptive (e.g., "simple red square")
- Replace the description for all styles in the release data directory, and the empty one too
- Replace the description for point/line/polygon/raster/generic also in the code, see the ``default_*.sld`` files in this package https://github.com/geoserver/geoserver/tree/master/src/main/src/main/java/org/geoserver/config

**Comment by Gnafu** [comment]
The styles have been updated on the EUMETSAT DEV server.

**Comment by imranrajjad** [comment]
https://github.com/geoserver/geoserver/pull/3916

**Comment by simboss** [comment]
@imranrajjad once this gets merged on master there are two things you should do:

1. cherrypick changes to [this](https://github.com/geosolutions-it/geoserver/tree/EOWS-158) branch
2. propose a backport to GeoServer community for 2.16.x

**Comment by aaime** [comment]
@imranrajjad in addition to the PR review:
* Names should be short but descriptive ("Red square point" is fine for example).
* Check visually the description matches the appearance
* If the abstract or other parts are inconsistent, fix them
* No need to change all data dirs, the release and empty ones are sufficient (and the "default_*.sld" styles in the code, no need to change the test ones).

**Comment by simboss** [comment]
@imranrajjad once this gets merged on master, please propose the backport to 2.16.x right away.

When that is merged, cherry pick changes to our eum branch (the one indicated above).

Careful with the cherry pick!

**Comment by imranrajjad** [comment]
PR for project branch https://github.com/geosolutions-it/geoserver/pull/121

Backport to 2.16.x https://github.com/geoserver/geoserver/pull/3919
