### ISSUE TITLE
Ability to throttle importer tasks

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/eumetsat-EOWS#157]
At the moment there is no way to control the parallelism of importer asynch tasks.

This task is about exposing the configuration of internal ingestion pool in GeoServer for managing parallel ingestions

**Comment by simboss** [comment]
Client has not accepted this one, but I would try to squeeze it in anyway.

**Comment by Gnafu** [comment]
This needs to be ported to https://github.com/geosolutions-it/geoserver/tree/EOWS-158

**Comment by simboss** [comment]
@Gnafu did you check if this has been already ported?
I remember it has been ported already.

**Comment by simboss** [comment]
@Gnafu you are right on this one, @aaime will do the backport shortly.

@aaime once you are done let us know so @Gnafu will deploy and test.
