### ISSUE TITLE
DBMS Shared Storage for Importer Tasks Status - WMS-PLP-ING-0700

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/eumetsat-EOWS#158]
We will publish on all the 6 instances in the cluster. 

if we need to use the importer on multiple instances in parallel we need to allow them to share the status likewise we do for WPS otherwise status calls for asynch tasks might fail.
I would use a pluggable architecture with an implementation for Postgres.

**Comment by simboss** [comment]
as you wish

**Comment by simboss** [comment]
As per our discussion, it would be best if we could also somehow group together the "cluster" related extensions and have a packaging profile to have them put inside the WAR.

**Comment by Gnafu** [comment]
@taba90 can you please estimate the backport of this work to the 2.16.x branch?

**Comment by nmco** [comment]
@taba90 can you confirm that is has been done?

**Comment by taba90** [comment]
@nmco as agreed with @Gnafu , at the moment backports have been made on a new branch available [here ](https://github.com/geosolutions-it/geoserver/tree/EOWS-158)
