### ISSUE TITLE
Support to CGI for new cluster implementation

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/eumetsat-EOWS#160]
**REQ: WMS-DEP-SYS-0236**
```
A minimum of 6 instances of GeoServer slaves and one instance of GeoServer master shall be deployed in the WMS cluster. 
Each instance shall have:
- A visualizations storage space shared among all instances (80 TB per year, see WMS-DEP-SYS-0240).
- An instance-dedicated hybrid storage space (1 TB for each instance).
- At least 32 GB of RAM.
- At least 8 Intel(R) Xeon(R) CPU E5-2695 v4 @ 2.10GHz or similar.
```

**Comment by Gnafu** [comment]
Import should be load-balanced on the slaves as well (requires latest fixes)
/importer

**Comment by Gnafu** [comment]
Rosa is setting up the new cluster.
It is accessible trough a jump host:
```
ssh geosolutions@54.93.154.227
kubectl get pods -n geosolutions
```

The load balancer for the importer is going to be set up by Rosa as soon as possible.

**Comment by Gnafu** [comment]
Current env deploy:
https://docs.google.com/presentation/d/1rg0pR-anI4V0tFoKZ09BuFjV0_ek1vLrI4gcDSiviZk/edit#slide=id.g6e57851ef3_0_54
