### ISSUE TITLE
Upgrade Docker Image for GeoServer

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/eumetsat-EOWS#161]
**WMS-DEP-SYS-0230**
In the light of the updates we are doing we should strive to create a new docker image for GeoServer.

We should also share the docker file with them so that they can build everything themselves

Inital requirement is **REQ: WMS-DEP-SYS-0230**:
*The WMS shall be deployed on a production-grade Kubernetes cluster on the ICSI MCD.*

**Comment by simboss** [comment]
Let's start with a Docker image that we build from our own 2.16.x branch for GeoServer.

**Comment by Gnafu** [comment]
Image created.
Now testing in DEV.
