### ISSUE TITLE
Support to CGI for CI/CD setup

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/eumetsat-EOWS#163]
**REQ: WMS-DEP-SYS-0280**
`A continuous integration (CI) and continuous deployment (CD) pipeline shall be established for the WMS, using the EUMETSAT GitLab and Jenkins.`

**Comment by Gnafu** [comment]
Need to push to harbor

**Comment by Gnafu** [comment]
Must be setup the datadir in the slaves
