### ISSUE TITLE
Specify AOI in the GUI for download

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/eumetsat-EOWS#165]
**WMS-PLP-GUI-1310**

The GUI shall provide a way to specify an Area of Interest (AOI) using the mouse and/or manually inserting the coordinates. The following operations will be available on the AOI: zoom on AOI, download data in the AOI.

**Comment by simboss** [comment]
"Not sure this impacts us.

In the current download which is based on WPS download we can already send a AOI as a polygon and that should work.
The raster download also takes a CQL filter, that gets passed down into the mosaic machinery. Not as easy as a straight time parameter, but workable.

Adding some support time, just in case. I do not expect to do much."

**Comment by Gnafu** [comment]
TODO:
- Send Mail to Alessandro Marin with references on how to specify the ROI on a WPS Download request

**Comment by Gnafu** [comment]
Mail sent
