### ISSUE TITLE
WMS-PLP-GUI-1320 - Better Overlays for animations and products

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/eumetsat-EOWS#166]
**WMS-PLP-GUI-1320**

The user shall be able to download images and animations for a single product featuring an overlay showing the product's corresponding legend (where available).

**Comment by simboss** [comment]
Animations support decoration layouts, which in turn allow to add a legend, but there is little control, like, it's the legend of all layers. I've added some days of work under the assumption we want to do some work to improve the legend appearance or filter its contents

**Comment by simboss** [comment]
@aaime what do you need from the current PROD configuration in order to move on with this?

**Comment by Gnafu** [comment]
I provided a simple test layout to Stefano.
Most of the layers have the "raster" style that does not produce a legend
The other layers with a palette still use a static image as legend

**Comment by Gnafu** [comment]
It looks like the static legend is not used by the "legend" decorator

**Comment by Gnafu** [comment]
I opened a JIRA for the wrong decorator behavior: https://osgeo-org.atlassian.net/browse/GEOS-9508

I also stumbled upon 2 known non-blocking bugs:
https://osgeo-org.atlassian.net/browse/GEOS-5188 -> Legend size can only be "auto"
https://osgeo-org.atlassian.net/browse/GEOS-6175 -> Auto-sized legend cuts the title text

**Comment by simboss** [comment]
@Gnafu open dependent issues and talk to @nmco about solving them.

@nmco we can use @taba90 for these ones

**Comment by nmco** [comment]
@Gnafu this one looks like an EPIC, could you open dependent issues?

**Comment by Gnafu** [comment]
@taba90 fixed everything and we are tracking it under https://app.zenhub.com/workspace/o/geosolutions-it/eumetsat-eows/issues/293
We are just waiting for travis build to confirm the fix

**Comment by nmco** [comment]
Ok understood, thx @Gnafu for the feedback.

**Comment by taba90** [comment]
pr for GEOS-5188 https://github.com/geoserver/geoserver/pull/4096

**Comment by Gnafu** [comment]
Turned out WPS the DownloadMap and DownloadAnimation  processes were not designed to have the legend decorator at all.
Development time will be needed for this.
