### ISSUE TITLE
WMS-PLP-ACC-1530 - More predefined styles for raster data

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/eumetsat-EOWS#168]
**WMS-PLP-ACC-1530**

The user shall be able to choose which colour palette to apply to display a product (in case of different colour palettes available for that product). Such feature shall be available both in API and GUI access.

**Comment by aaime** [comment]
There is also the dynamic palette community module that allows to pick a palette and stretch the style values based on layer stats... but we need the stats to be computed in advance.

**Comment by Gnafu** [comment]
After discussing with EUM we are just talking about a set of predefined styles.

TODO: define how these styles

**Comment by Gnafu** [comment]
TODO:
- [ ] Publish the samples we have on dropbox
- [ ] Link the dropbox folders to the spreadsheet
- [ ] Add information about the images (RGS/GRAY/COLORMAP) to the spreadsheet

**Comment by Gnafu** [comment]
Sent info to Stefano Marra with a layer that has multiple associated styles.
Found out the styles do not appear in the GetCapabilities document if the user has no access to the data.

**Comment by Gnafu** [comment]
Everything sent from Fabrizio has been set up
