### ISSUE TITLE
Collect information about current PROD

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/eumetsat-EOWS#173]
@Gnafu can you collect information about current PROD (version of GeoServer, version of PGis, etc..) and create a small doc inside the drive folder for the project.

**Comment by Gnafu** [comment]
Prod is currently unreachable

**Comment by Gnafu** [comment]
We have access to DEV and PROD again.
Need to review all the Layers security configuration

**Comment by Gnafu** [comment]
Updating this https://docs.google.com/document/d/1Av4F14sPWYpzfFCRyhbAOEsTOOV26BpC57o3vjhoajY/edit#
