### ISSUE TITLE
GetFeatureInfo does not work on wind-reduced layer

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/eumetsat-EOWS#18]
As per subject, I get an exception when I do a GetFeatureInfo on the wind-reduced layer.

We should investigate why this is happening.

**Comment by Gnafu** [comment]
I just changed a column type to further reduce the size, it is now 15% smaller than the original.
I reloaded the featuretype in GeoServer, the GetFeatureInfo is now working.
