### ISSUE TITLE
Improve Shapefiles Import

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/eumetsat-EOWS#187]
Investigate alternatives for ShapeFiles upload. They could potentially be huge.

**Comment by simboss** [comment]
Right now ASK is sending the Shapefile via POST Upload, I would prefer to have a mechanism where they deliver the file on a shared filesystem or in the Object Storage and we pull them from there.

This requires us to do some work at the importer level but also them to slightly update the ingestion.

**Comment by simboss** [comment]
This is on hold for the moment.
