### ISSUE TITLE
Remote file system is slow

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/eumetsat-EOWS#194]
https://cgi-pathfinders.atlassian.net/browse/IMGMT-22?atlOrigin=eyJpIjoiOTQ2ODNlNzFhOTJiNDMyMTkzNjMzNjliMWFlYTE0ODkiLCJwIjoiaiJ9

**Comment by Gnafu** [comment]
CGI Investigation is on hold, they are moving to another cluster so the performance will be tested on the new one.

**Comment by Gnafu** [comment]
No issues found on the new cluster.
Still need to do an actual performance test

**Comment by simboss** [comment]
I would close this for the moment though.
