### ISSUE TITLE
Check importer return codes

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/eumetsat-EOWS#196]
From kostyuka:
```
After the ingestion is complete,  the Ingestion Service sends a request to the GeoServer using
http method
DELETE (to delete the ingestion session). 
The GeoServer  responded with the status code
204 NO_CONTENT, 
while the service was expecting the status 
200 OK.
Therefore, the Ingestion Service produces a warning message in  the log, e.g.


2019-12-23 09:09:44.409 +0000 [taskExecutor-5         :3a3e4489-9bd1-4642-9784-0e2de8e54fa0] WARN  org.eumetsat.eows.wms.ingservice.service.StorageServiceImpl                 :
Unexpected status code after deleting import: 204 NO_CONTENT

```
https://cgi-pathfinders.atlassian.net/browse/IMGMT-25

Investigate if the importer API changed or the importer jobs are deleted in any other way.

**Comment by simboss** [comment]
This come from the client 

> Please check what should be the right response on the DELETE request. 
> Either the code of the GeoServer has to be corrected or, if “204 NO_CONTENT” response  is the expected behavior,  I have to change the WMS Ingestion Service code so that it expects the 204 status and does not produce warnings.

It is important to understand why we now send back a 204 and decide if that is fine and so the downstream code should be updated by our partners.

**Comment by nmco** [comment]
@imranrajjad 204 looks correct in this case althought 200 is fine too, check:
https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html#sec9.7

I would spend 30 minutes understand when was this changed and why. It would be good to validate that 204 is indeed valid in this case (no entity returned in the response). @imranrajjad please check whit @Gnafu for more details about what's exactly the query send by the client or at least in whit context.

**Comment by imranrajjad** [comment]
@nmco 

The code is hard coded as response type of controller method. Please see here [ImportController.deleteImports](https://github.com/geoserver/geoserver/blob/master/src/extension/importer/rest/src/main/java/org/geoserver/importer/rest/ImportController.java#L130)

I was not able to find the Pull request for this change, however doing a bit of digging in git blame. This is where this code appears,

```
commit bfe928290a451255063cfedea8f27f4266a56e6d
Author: Torben Barsballe <tbarsballe@boundlessgeo.com> 2017-04-06 23:06:16
Committer: Torben Barsballe <tbarsballe@boundlessgeo.com> 2017-04-06 23:06:16
Parent: 6ead91002785659f349dd94bca4590dd782c06c5 (Refactor org.geoserver.catalog.rest to org.geoserver.rest.catalog)
Child: d9153ce39b784cbc035ec8308aba6188bfd43f29 (Importer rest - fix up response codes, support POST to id when import exists)

Fixup import PUT by id, add support for import DELETE
```

**Comment by simboss** [comment]
@imranrajjad thanks for the info but the question I have now is the following.

Is 204 correct in this context or not? I thin k so but still...
Talk to the others on our geoserver channel is needed and let me know..

**Comment by imranrajjad** [comment]
@simboss sure, I will and back to you

**Comment by aaime** [comment]
204 means "success, won't return a body in the response". It's a common response for delete, since there is rarely a response payload to go with it.

**Comment by nmco** [comment]
Yes at this stage @imranrajjad the only thin you need to do is:
- Ask @Gnafu for more details about the request that's actually sent (I guess you already did it).
- Does that DELETE requests returns a payload? If YES then 200, otherwise 204 is the correct one, quoting the standard linked above:

> A successful response SHOULD be 200 (OK) if the response includes an entity describing the status, 202 (Accepted) if the action has not yet been enacted, or 204 (No Content) if the action has been enacted but the response does not include an entity.

**Comment by simboss** [comment]
@imranrajjad so the final asnwer is ?

**Comment by imranrajjad** [comment]
@simboss the correct answer is

(drum rolls)

204 is the correct code, since running the unit test and code review reveals that the controller is not writing any response back to client making REST calls. 204 code assures that whatever Id that was sent  to be deleted as been deleted and no other confirmation is required (e.g an XML or JSON response with message "resource xyz has been deleted) etc

**Comment by Gnafu** [comment]
closing
