### ISSUE TITLE
Create a style with windbarbs

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/eumetsat-EOWS#2]
Verify source data is compatible with a windbarbs style and create it.

**Comment by simboss** [comment]
Apparently we are hitting a minor issue that is blocking is. See #14.

**Comment by simboss** [comment]
@Gnafu please, update this ticket

**Comment by Gnafu** [comment]
A workaround for #14 is in place.
I move this back to backlog to update the style once #14 is fixed
