### ISSUE TITLE
Check if GeoServer can handle multiple groups in a body response

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/eumetsat-EOWS#202]
Currently the "AuthKEY WebService Body Response UserGroup Service" is parsing a single group from the response.
It needs to be able to parse an array of groups

It is currently parsing bodies like:
```
{"username":"licensed_user_e","roles":"REGISTERED_LICENSED"}
```
with the regex
```
^.*?"roles"\s*:\s*"([^"]+)".*$
```

It will need to parse and array of roles:
```
{"username":"licensed_user_e","roles":["LICENSE1", "LICENSE2"]}
```

**Comment by simboss** [comment]
@mbarto do you have any feedback for this?

**Comment by Gnafu** [comment]
GeoServer supports a comma separated list out of the box, so if the "roles" value is "LICENSE1,LICENSE2" we get this functionality for free.

If the service returns an actual array, the regex must be able to parse is with the grouping syntax "()".

We are proposing CGI to go for the first implementation

**Comment by Gnafu** [comment]
Confirmed.
Geoserver will parse a comma separated list of licenses (groups) from the AuthKEY WebService Body Response with the current configuration.
