### ISSUE TITLE
Review new EUMETSAT data

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/eumetsat-EOWS#213]
We should review the new data EUMETSAT gave us.

Todo:
- Open an issue for each class
- GDALINFO to know what's in there:
 -- How many bands
 -- 
- Check if optimization is needed, and which one.

NOTES:
- They want color fidelity, so use lossless compressions

**Comment by Gnafu** [comment]
@ElenaGallo The files received from EUMETSAT are ordered differently than the Data Specification spreadsheet.
Please create an issue with:
- Title: <the folder name> - <the class name>
- Description: the "product_name" (if found on a json file inside the folder) and the data analysis

**Comment by randomorder** [comment]
you know of this uber-epic still relevant @simboss ?
