### ISSUE TITLE
metopa_ascat_scatterometer_wind_thinned_platecarree - EPS M01 ASCAT Wind BUFR as Shapefile

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/eumetsat-EOWS#223]
Same as the metopa files we know:

INFO: Open of `MetopB_ScatterometerWind_ASCAT_Thinned_PlateCarree_2002270306.zip'
using driver `ESRI Shapefile' successful.

Layer name: Wind-LODs-ascat_20200227043600_metopb_XXXXX_eps_o_coa_ovw
Geometry: Point
Feature Count: 144508
Extent: (-115.625259, -72.401703) - (97.598190, 48.588570)

Layer SRS WKT:
GEOGCS["WGS 84",
DATUM["unknown",
SPHEROID["WGS84",6378137,298.257223563]],
PRIMEM["Greenwich",0],
UNIT["degree",0.0174532925199433],
AXIS["Longitude",EAST],
AXIS["Latitude",NORTH]]

Data axis to CRS axis mapping: 1,2

WIND SPEED: Real (50.10)
WIND DIREC: Real (50.10)
BACKSCATTE: Real (50.10)
LOD: Real (50.0)

**Comment by Gnafu** [comment]
This same sample will be the same for:
- MetopA
- MetopB
- MetopC

**Comment by Gnafu** [comment]
All 3 layers have been deployed on dev

**Comment by ElenaGallo** [comment]
On the client side,  this layer is not visible on map.
