### ISSUE TITLE
WFS export from MapStore2 will not work

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/eumetsat-EOWS#25]
Due to [this bug](https://github.com/geosolutions-it/MapStore2/issues/2168) the data export of the wind data using MapStore2 is not currently possible.

A temporary workaround is to add cloudsdi url to the known servers of the MapStore2 demo instance.

```
"proxyUrl": {
        "url": "/mapstore/proxy/?url=",
        "useCORS": ["http://demo.geo-solutions.it/geoserver", "https://demo.geo-solutions.it/geoserver", "http://cloudsdi.geo-solutions.it:80/geoserver", "http://cloudsdi.geo-solutions.it/geoserver"]
    },
```

**Comment by Gnafu** [comment]
The workaround is applied to our demo.
http://mapstore2.geo-solutions.it/mapstore/#/viewer/leaflet/2940

NOTE: Since cloudsdi server does not yet have https, this workaround will not work if MapStore2 is loaded over https.

**Comment by simboss** [comment]
@Gnafu let's synch tomorrow about this

**Comment by Gnafu** [comment]
The export is now working in DEV too but if we select the "Native" option, the exported data will be in the wrong crs. I'm investigating on this.

**Comment by Gnafu** [comment]
Apparently the native export works correctly as GeoServer provides the correct data with the correct projection information.
It is the shapefile import function that is not correctly parsing the projection info.
It is tracked by this issue: https://github.com/geosolutions-it/MapStore2/issues/2175
