### ISSUE TITLE
msgiodc_naturalenhncd - MSG HR IODC RGB Natural Clour Enhncd.

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/eumetsat-EOWS#265]
*product_name*: `"MET8_RGBTrueColour_PlateCarree"`

File= `MET8_RGBTrueColour_PlateCarree_2002121430.tif`
File Size= `21.935 KB`
Format= `GeoTIFF`
Size= `3712, 3712 pixels`
Compression= `DEFLATE`    
Band= `3`  
Type= `Byte`
Color Interpretation= `RGB`
Overviews= `yes`   

**GDALINFO**

>Driver: GTiff/GeoTIFF
Files: MET8_RGBTrueColour_PlateCarree_2002121430.tif
Size is 3712, 3712
Coordinate System is:
GEOGCRS["WGS 84",
    DATUM["World Geodetic System 1984",
        ELLIPSOID["WGS 84",6378137,298.257223563,
            LENGTHUNIT["metre",1]]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433]],
    CS[ellipsoidal,2],
        AXIS["geodetic latitude (Lat)",north,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433]],
        AXIS["geodetic longitude (Lon)",east,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433]],
    ID["EPSG",4326]]
Data axis to CRS axis mapping: 2,1
Origin = (-35.500000000000000,77.000000000000000)
Pixel Size = (0.041487068965517,-0.041487068965517)
Metadata:
  AREA_OR_POINT=Area
TIFFTAG_DOCUMENTNAME=/home/sysops/IPPS//modules/MET8_RGBTrueColour_PlateCarree/frames/trivis.00000.tif
  TIFFTAG_RESOLUTIONUNIT=1 (unitless)
  TIFFTAG_XRESOLUTION=72
  TIFFTAG_YRESOLUTION=72
Image Structure Metadata:
  COMPRESSION=DEFLATE
  INTERLEAVE=PIXEL
Corner Coordinates:
Upper Left  ( -35.5000000,  77.0000000) ( 35d30' 0.00"W, 77d 0' 0.00"N)
Lower Left  ( -35.5000000, -77.0000000) ( 35d30' 0.00"W, 77d 0' 0.00"S)
Upper Right ( 118.5000000,  77.0000000) (118d30' 0.00"E, 77d 0' 0.00"N)
Lower Right ( 118.5000000, -77.0000000) (118d30' 0.00"E, 77d 0' 0.00"S)
Center      (  41.5000000,   0.0000000) ( 41d30' 0.00"E,  0d 0' 0.01"N)
Band 1 Block=512x512 Type=Byte, ColorInterp=Red
  NoData Value=0
  Overviews: 1856x1856, 928x928, 464x464, 232x232, 116x116
Band 2 Block=512x512 Type=Byte, ColorInterp=Green
  NoData Value=0
  Overviews: 1856x1856, 928x928, 464x464, 232x232, 116x116
Band 3 Block=512x512 Type=Byte, ColorInterp=Blue
  NoData Value=0
  Overviews: 1856x1856, 928x928, 464x464, 232x232, 116x116

**Comment by ElenaGallo** [comment]
On MapStore there is a BLUE_BAND = 1.0 behind the `MET8_RGBTrueColour_PlateCarree_2002130915.tif`, as seen below:

![msg_iodc_rgb_naturalenhncd](https://user-images.githubusercontent.com/56537133/75870887-f7025d80-5e0b-11ea-9192-5c4432e5fcf8.JPG)

**Comment by Gnafu** [comment]
Linking #320 but probably not an issue.
