### ISSUE TITLE
sentinel3ab_accumulated_olci_l2_oceancolor_redres_platecarre - Copernicus S3A/B OC4Me CHL Daily

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/eumetsat-EOWS#287]
File= `chloc4me_s3ab_accu_daily_2002120010_2002121117.tif`
File Size= `45 MB`
Format= `GeoTIFF`
Size= `28953, 15224 pixels`
Compression= `DEFLATE`    
Band= `1`  
Type= `Float32`
Color Interpretation= `Gray`
Overviews= `yes`   

**GDALINFO**

>Driver: GTiff/GeoTIFF
Files: chloc4me_s3ab_accu_daily_2002120010_2002121117.tif
Size is 28953, 15224
Coordinate System is:
GEOGCRS["WGS 84",
    DATUM["World Geodetic System 1984",
        ELLIPSOID["WGS 84",6378137,298.257223563,
            LENGTHUNIT["metre",1]]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433]],
    CS[ellipsoidal,2],
        AXIS["geodetic latitude (Lat)",north,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433]],
        AXIS["geodetic longitude (Lon)",east,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433]],
    ID["EPSG",4326]]
Data axis to CRS axis mapping: 2,1
Origin = (-116.027509299095072,67.876816858289430)
Pixel Size = (0.010000000000000,-0.010000000000000)
Metadata:
  AREA_OR_POINT=Area
Image Structure Metadata:
  COMPRESSION=DEFLATE
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  (-116.0275093,  67.8768169) (116d 1'39.03"W, 67d52'36.54"N)
Lower Left  (-116.0275093, -84.3631831) (116d 1'39.03"W, 84d21'47.46"S)
Upper Right ( 173.5024907,  67.8768169) (173d30' 8.97"E, 67d52'36.54"N)
Lower Right ( 173.5024907, -84.3631831) (173d30' 8.97"E, 84d21'47.46"S)
Center      (  28.7374907,  -8.2431831) ( 28d44'14.97"E,  8d14'35.46"S)
Band 1 Block=512x512 Type=Float32, ColorInterp=Gray
  NoData Value=nan
  Overviews: 14477x7612, 7239x3806, 3620x1903, 1810x952

**Comment by ElenaGallo** [comment]
On MapStore a black rectangle is visible in some granules of the mosaic, as seen below:

![6](https://user-images.githubusercontent.com/56537133/75873178-c3293700-5e0f-11ea-9057-706a2326844d.JPG)

**Comment by ElenaGallo** [comment]
On the client side,  this layer is not visible on map.

**Comment by Gnafu** [comment]
Same as #290
