### ISSUE TITLE
Fix decorator legend

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/eumetsat-EOWS#293]
~ Details in https://osgeo-org.atlassian.net/browse/GEOS-9508 ~

Updated, now the issue is in the WPS Download plugin: https://osgeo-org.atlassian.net/browse/GEOS-9531

We need a fix in the gs:DownloadMap and the gs:DownloadAnimation processes

**Comment by taba90** [comment]
Pull request https://github.com/geoserver/geoserver/pull/4074/commits/da7336b81f136fa8dccaf72e1f61a2277bb359e8

**Comment by nmco** [comment]
What's the status of this @taba90? the link above points to a commit.

**Comment by Gnafu** [comment]
@nmco  The pull request is ready, waiting for a review https://github.com/geoserver/geoserver/pull/4074

**Comment by nmco** [comment]
Understood thx for the feedback @Gnafu.

**Comment by Gnafu** [comment]
Backport to custom branch is failing to show correct legends.
Travis build passed.
Marco is investigating

**Comment by Gnafu** [comment]
WMS works correctly.
WPS  gs:DownloadMap process does not add the legend.
Will open a new Jira for this

**Comment by Gnafu** [comment]
Here it is: https://osgeo-org.atlassian.net/browse/GEOS-9531

**Comment by nmco** [comment]
Only backport remains, @taba90 is working on it.

**Comment by Gnafu** [comment]
Turned out WPS the DownloadMap and DownloadAnimation processes were not designed to have the legend decorator at all.
Development time will be needed for this.

**Comment by nmco** [comment]
JIRA ticket:
https://osgeo-org.atlassian.net/browse/GEOS-9531

This is for:
```
EUMETSAT - CGI
C068-EUMETSAT-CGI-2019-WP2
```

@taba90 as usual initial investigation, the plan and estimate before moving on whit the work.

**Comment by simboss** [comment]
@taba90 please, give priority to delivering to EUM.

For this scenario we just need the legend working on a sinle layer at a time.
If multiple layers are requested for the moment you can simply not show anything.

**Comment by taba90** [comment]
fix has been backported to client branch https://github.com/geosolutions-it/geoserver/tree/EOWS-158

**Comment by simboss** [comment]
@Gnafu this is for you!

**Comment by taba90** [comment]
Following issues have also found and fixed:
https://osgeo-org.atlassian.net/browse/GEOS-9540
https://osgeo-org.atlassian.net/browse/GEOS-9541
Fixes have been backported to https://github.com/geosolutions-it/geoserver/tree/EOWS-158

**Comment by taba90** [comment]
this issue still need to be fixed https://osgeo-org.atlassian.net/browse/GEOS-9542

**Comment by Gnafu** [comment]
@taba90 I see the fix has been fixed on the master branch.
Please let me know when the fix is on the EOWS-158 branch as well

**Comment by taba90** [comment]
@Gnafu the fix is on EOWS-158 branch too
