### ISSUE TITLE
Freeze geotools version in the custom branch

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/eumetsat-EOWS#295]
Do not use geotools snapshot dependencies in the EOWS-158 branch

Do:
- [x] Create a custom Geotools branch
- [x] Create a custom GeoWebCache branch
- [x] Set GeoServer custom branch to use the custom GeoTools and GeoWebcache artifacts
- [x] Setup the build jobs to build and deploy it
- [x] Push the changes to Eumetsat Gitlab

**Comment by Gnafu** [comment]
@aaime does this means that we also need to have a custom branch of geowebcache?

**Comment by simboss** [comment]
@Gnafu my questions is why you did not bring this up during our last synch.

This is obviously a priority. Let's put it in ready and then decide who does what.

@randomorder is this something we can throw at someone? Aman? Giacomo?

**Comment by aaime** [comment]
@Gnafu having a custom branch of GWC too would be ideal, not sure it's strictly needed, [GWC 1.16.x has been moving very slowly](https://github.com/GeoWebCache/geowebcache/commits/1.16.x).
But if we want complete control, it's mandatory to also lock down GWC, yes.

**Comment by randomorder** [comment]
> @randomorder is this something we can throw at someone? Aman? Giacomo?

As soon as @Gnafu created the branches and updated the POMs it's straightforward to set up the builds.

Draft build jobs are here:
- [GT](https://build.geo-solutions.it/jenkins/view/Eumetsat%20-%20EOWS/job/GeoTools%20EOWS-158/)
- [GWC](https://build.geo-solutions.it/jenkins/view/Eumetsat%20-%20EOWS/job/GeoWebCache%20EOWS-158/)
- [GS](https://build.geo-solutions.it/jenkins/view/Eumetsat%20-%20EOWS/job/GeoServer%20EOWS-158/)

They are currently disabled and tracking the EOWS-158 on the `geosolutions-it` fork of the projects.
I can finish the setup of the builds as soon as the poms are updated

**Comment by Gnafu** [comment]
@randomorder The branches are updated.

**Comment by randomorder** [comment]
Hi @Gnafu 
I updated the builds. Please check their status. Let me know if I missed something.

**Comment by randomorder** [comment]
There are issues with GWC and GS builds. See also [here](https://github.com/geosolutions-it/eumetsat-EOWS/issues/325)

Also, I'll add the deploy profile to publish the artifacts

**Comment by randomorder** [comment]
GT and GWC artifacts [here](http://maven.geo-solutions.it/org/geowebcache/gwc-web/1.16-EOWS-SNAPSHOT/) and [here](http://maven.geo-solutions.it/org/geotools/gt-main/22-EOWS-SNAPSHOT/)
