### ISSUE TITLE
Ingest Sample Data

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/eumetsat-EOWS#3]
We have multiple data to ingest in our cloudsdi server on AWS in order to start interacting with the EOWS team.

We will then move to the dockerize infrastructure wherever that will be.

On the new infrastructure we should make use of the parameterized configuration for paths, DBMS connections and so on.

**Comment by simboss** [comment]
@Gnafu you should like related issue in this one.

**Comment by Gnafu** [comment]
- [ ] Ingest AMV NetCDF Data #26
- [ ] More Sample Data #11
