### ISSUE TITLE
Proxy issue with Rancher

### ISSUE THREAD

**Issue by randomorder** [geosolutions-it/eumetsat-EOWS#30]
We are having issues using Rancher UI in development environment. This is likely an issue with proxy configuration.
I am collecting more information for debugging.

**Comment by randomorder** [comment]
By opening the browser in debug mode while trying to login into Rancher I found the following:
Some requests are made against the correct hostname ( http://pf-rancher.eoss-cloud.it/ ) while others are not.

For instance,
good request: https://goo.gl/k4Bom3
bad request:  https://goo.gl/cZzJNR

Latter request is made against a "*.local" domain name and results in a timeout error

**Comment by randomorder** [comment]
Fabio D'Andria and I fixed proxy issue with GeoServer, however some Proxy related issues with Rancher still exist. Currently we cannot "Upgrade" services via Rancher UI because the upgrade request times out

**Comment by randomorder** [comment]
Also noticed GeoServer Layer preview is working for GeoServer Master but not for GeoServer Cluster:
working here: https://pf-docker.eoss-cloud.it/geoserver-master/
not working here: https://pf-docker.eoss-cloud.it/geoserver/

**Comment by simboss** [comment]
@randomorder any news?

**Comment by randomorder** [comment]
Still not working. I'll re-ping Angela Cataldo and Fabio D'Andria about it

**Comment by randomorder** [comment]
CGI tried to fix this several times but still not working. I am afraid we'll not get this one fix in the current DEV infrastructure
