### ISSUE TITLE
Add Nearest Match to all the mosaics

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/eumetsat-EOWS#300]
The "Nearest Match" must be added to all the products that have a TIME dimension
The Interval must cover the past only, with enough range to reach the previous sample.
For example:
- If the granules are 15 minutes apart: PT15M/PT0H
- If the granules are 3 hours apart: PT3H/PT0H
- Metop1/2/3: PT98M/PT0H

**Comment by Gnafu** [comment]
@ElenaGallo is this done?

**Comment by ElenaGallo** [comment]
@Gnafu 
is it PT24H/PT0H the "Nearest Match" for the Metop with TIME= 24hrs?
is it PT100M/PT0H the "Nearest Match" for the Copernicus with TIME= 100.9 min?

**Comment by Gnafu** [comment]
> is it PT24H/PT0H the "Nearest Match" for the Metop with TIME= 24hrs?

Some GeoTiff mosaics may have 24hrs sensing time, for example EO:EUM:DAT:0190: in those cases, please check the actual time difference between the granules and pick a range that covers it.

> is it PT100M/PT0H the "Nearest Match" for the Copernicus with TIME= 100.9 min?

Again, check the actual granules time difference, if they are indeed 100.9 minutes apart, just use 101 minutes for the nearest match

**Comment by Gnafu** [comment]
@ElenaGallo is there an update on this?
Thank you

**Comment by ElenaGallo** [comment]
I have added the "Nearest Match" to all the products that have a TIME dimension
