### ISSUE TITLE
eps_osisaf_avhrr_l3_sst - OSI SAF Metop AVHRR L3 SST

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/eumetsat-EOWS#302]
File= `S-OSI_-FRA_-MTOP-GLBSST_FIELD-202002261200Z.nc`
File Size= `49.825 KB`
Format= `NetCD`
Size= `3600x7200 pixels`

**GDALINFO**

>Driver: netCDF/Network Common Data Format
Files: S-OSI_-FRA_-MTOP-GLBSST_FIELD-202002261200Z.nc
Size is 512, 512
Metadata:
  NC_GLOBAL#acknowledgment=In case SAF data (pre-operational or operational) has been used for the study described in a paper the following sentence would be an appropriate reference to the funding coming from EUMETSAT: The data from the EUMETSAT Satellite Application Facility on Ocean & Sea Ice  used in this study are accessible through the SAF's homepage http://www.osi-saf.org
  NC_GLOBAL#cdm_data_type=grid
  NC_GLOBAL#comment=
  NC_GLOBAL#Conventions=CF-1.4
  NC_GLOBAL#creator_email=osi-saf.helpdesk@meteo.fr
  NC_GLOBAL#creator_name=O&SI SAF
  NC_GLOBAL#creator_url=http://www.osi-saf.org
  NC_GLOBAL#date_created=20200226T184930Z
  NC_GLOBAL#easternmost_longitude=180
  NC_GLOBAL#file_quality_level=3
  NC_GLOBAL#gds_version_id=2.0
  NC_GLOBAL#geospatial_lat_resolution=0.05
  NC_GLOBAL#geospatial_lat_units=degrees_north
  NC_GLOBAL#geospatial_lon_resolution=0.05
  NC_GLOBAL#geospatial_lon_units=degrees_east
  NC_GLOBAL#history=METEO-FRANCE/CMS LEOSAFO processor
  NC_GLOBAL#id=AVHRR_SST_METOP_B_GLB-OSISAF-L3C-v1.0
  NC_GLOBAL#institution=OSISAF
  NC_GLOBAL#keywords=Oceans > Ocean Temperature > Sea Surface Temperature
  NC_GLOBAL#keywords_vocabulary=NASA Global Change Master Directory (GCMD) Science Keywords
  NC_GLOBAL#license=All intellectual property rights of the Ocean & Sea Ice SAF products belong to EUMETSAT. The use of these products is granted to every user, free of charge. If users wish to use these products, EUMETSAT's copyright credit must be shown by displaying the words 'Copyright EUMETSAT' under each of the products shown. EUMETSAT offers no warranty and accepts no liability in respect of the Ocean & Sea Ice SAF products. EUMETSAT neither commits to nor guarantees the continuity, availability, or quality or suitability for any purpose of, the Ocean & Sea Ice SAF products.
  NC_GLOBAL#Metadata_Conventions=Unidata Dataset Discovery v1.0
  NC_GLOBAL#metadata_link=N/A
  NC_GLOBAL#naming_authority=org.ghrsst
  NC_GLOBAL#netcdf_version_id=4.4.1.1
  NC_GLOBAL#northernmost_latitude=90
  NC_GLOBAL#platform=METOP_B
  NC_GLOBAL#processing_level=L3C
  NC_GLOBAL#product_version=1.0
  NC_GLOBAL#project=Group for High Resolution Sea Surface Temperature
  NC_GLOBAL#publisher_email=ghrsst-po@nceo.ac.uk
  NC_GLOBAL#publisher_name=The GHRSST Project Office
  NC_GLOBAL#publisher_url=http://www.ghrsst.org
  NC_GLOBAL#references=Low Earth Orbiter Sea Surface Temperature Product User Manual, http://www.osi-saf.org
  NC_GLOBAL#sensor=AVHRR
  NC_GLOBAL#source=AVHRR
  NC_GLOBAL#southernmost_latitude=-90
  NC_GLOBAL#spatial_resolution=0.05 degree
  NC_GLOBAL#standard_name_vocabulary=NetCDF Climate and Forecast (CF) Metadata Convention
  NC_GLOBAL#start_time=20200226T055803Z
  NC_GLOBAL#stop_time=20200226T180103Z
  NC_GLOBAL#summary=The GLB L3C product derived from METOP B AVHRR brightness temperatures.
  NC_GLOBAL#time_coverage_end=20200226T180103Z
  NC_GLOBAL#time_coverage_start=20200226T055803Z
  NC_GLOBAL#title=Sea Surface Temperature
  NC_GLOBAL#uuid=B8D87708-58C8-11EA-8E32-2C44FD7FF654
  NC_GLOBAL#westernmost_longitude=-180
Subdatasets:
  SUBDATASET_1_NAME=NETCDF:"S-OSI_-FRA_-MTOP-GLBSST_FIELD-202002261200Z.nc":sea_surface_temperature
  SUBDATASET_1_DESC=[1x3600x7200] sea_surface_subskin_temperature (32-bit floating-point)
  SUBDATASET_2_NAME=NETCDF:"S-OSI_-FRA_-MTOP-GLBSST_FIELD-202002261200Z.nc":sst_dtime
  SUBDATASET_2_DESC=[1x3600x7200] sst_dtime (32-bit floating-point)
  SUBDATASET_3_NAME=NETCDF:"S-OSI_-FRA_-MTOP-GLBSST_FIELD-202002261200Z.nc":sses_bias
  SUBDATASET_3_DESC=[1x3600x7200] sses_bias (32-bit floating-point)
  SUBDATASET_4_NAME=NETCDF:"S-OSI_-FRA_-MTOP-GLBSST_FIELD-202002261200Z.nc":sses_standard_deviation
  SUBDATASET_4_DESC=[1x3600x7200] sses_standard_deviation (32-bit floating-point)
  SUBDATASET_5_NAME=NETCDF:"S-OSI_-FRA_-MTOP-GLBSST_FIELD-202002261200Z.nc":dt_analysis
  SUBDATASET_5_DESC=[1x3600x7200] dt_analysis (32-bit floating-point)
  SUBDATASET_6_NAME=NETCDF:"S-OSI_-FRA_-MTOP-GLBSST_FIELD-202002261200Z.nc":wind_speed
  SUBDATASET_6_DESC=[1x3600x7200] wind_speed (32-bit floating-point)
  SUBDATASET_7_NAME=NETCDF:"S-OSI_-FRA_-MTOP-GLBSST_FIELD-202002261200Z.nc":sea_ice_fraction
  SUBDATASET_7_DESC=[1x3600x7200] sea_ice_area_fraction (32-bit floating-point)
  SUBDATASET_8_NAME=NETCDF:"S-OSI_-FRA_-MTOP-GLBSST_FIELD-202002261200Z.nc":aerosol_dynamic_indicator
  SUBDATASET_8_DESC=[1x3600x7200] aerosol_dynamic_indicator (32-bit floating-point)
  SUBDATASET_9_NAME=NETCDF:"S-OSI_-FRA_-MTOP-GLBSST_FIELD-202002261200Z.nc":adi_dtime_from_sst
  SUBDATASET_9_DESC=[1x3600x7200] adi_dtime_from_sst (32-bit floating-point)
  SUBDATASET_10_NAME=NETCDF:"S-OSI_-FRA_-MTOP-GLBSST_FIELD-202002261200Z.nc":sources_of_adi
  SUBDATASET_10_DESC=[1x3600x7200] sources_of_adi (32-bit floating-point)
  SUBDATASET_11_NAME=NETCDF:"S-OSI_-FRA_-MTOP-GLBSST_FIELD-202002261200Z.nc":l2p_flags
  SUBDATASET_11_DESC=[1x3600x7200] l2p_flags (32-bit floating-point)
  SUBDATASET_12_NAME=NETCDF:"S-OSI_-FRA_-MTOP-GLBSST_FIELD-202002261200Z.nc":quality_level
  SUBDATASET_12_DESC=[1x3600x7200] quality_level (32-bit floating-point)
  SUBDATASET_13_NAME=NETCDF:"S-OSI_-FRA_-MTOP-GLBSST_FIELD-202002261200Z.nc":satellite_zenith_angle
  SUBDATASET_13_DESC=[1x3600x7200] satellite_zenith_angle (32-bit floating-point)
  SUBDATASET_14_NAME=NETCDF:"S-OSI_-FRA_-MTOP-GLBSST_FIELD-202002261200Z.nc":solar_zenith_angle
  SUBDATASET_14_DESC=[1x3600x7200] solar_zenith_angle (32-bit floating-point)
Corner Coordinates:
Upper Left  (    0.0,    0.0)
Lower Left  (    0.0,  512.0)
Upper Right (  512.0,    0.0)
Lower Right (  512.0,  512.0)
Center      (  256.0,  256.0)

**Comment by Gnafu** [comment]
sea_surface_temperature
sst_dtime
sses_bias
sses_standard_deviation
dt_analysis
wind_speed
sea_ice_fraction
aerosol_dynamic_indicator
adi_dtime_from_sst
sources_of_adi
l2p_flags
quality_level
satellite_zenith_angle
solar_zenith_angle

**Comment by ElenaGallo** [comment]
[Here](https://docs.google.com/document/d/1gAs7bfVgZsaHzKL8AKlBSLsJzijMf8SSjJ_uYpiZlis/edit?usp=sharing) the description of the pre-processing.

**Comment by ElenaGallo** [comment]
[Here](https://docs.google.com/document/d/1TWMaZxlDjMCFMH-QliOqFV0df_uHTSXrtNO-sX2rebg/edit?usp=sharing) the description of the pre-processing.
