### ISSUE TITLE
Eumetsat Data - Workspace error

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/eumetsat-EOWS#306]
There are two High Rate SEVIRI WV6.2 μm Image < 3hr - MSG - 0 degree layers. One of these is not aveilable.  It seems that the workspace is wrong. The wv062_nrt layer is located in msg_0deg not in the msg_fes store.

Here the error in console: 
> https://view.cgi-dev.de/geoserver/gwc/service/wmts?time=2020-02-28T08:30:00.000Z/2020-03-02T01:00:00.000Z&service=WMTS&version=1.0.0&request=GetHistogram&layer=msg_fes:wv062_nrt&histogram=time&tileMatrix=EPSG:4326&resolution=PT2H13M20S&access_token=0022e357-1cf1-311d-a446-ef1ff01b4ea1

**Comment by Gnafu** [comment]
Client should be fixed now
