### ISSUE TITLE
Questions about gridsets

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/eumetsat-EOWS#308]
@Gnafu my question here why we are stopping the grdisets at level 10?

I mean, the pilot client goes beyond this level and the background from OSM become very slow so we should really cache this!

Feedback?

**Comment by Gnafu** [comment]
That was probably done to limit the disk usage and prevent cache thrashing.
I can add more levels

**Comment by simboss** [comment]
I would go beyond this limit at least for the OSM layers due to their slowness.

What do you think?

**Comment by Gnafu** [comment]
Agree, this will need to:
- Increase the cache levels in the gridset definitions
- Restrict each layer's cache to level 10

But we can also just increase the cache levels for all layers and see what impact this has.

**Comment by simboss** [comment]
@Gnafu this is becoming prioritary..

**Comment by Gnafu** [comment]
Done
