### ISSUE TITLE
Layer problems on the client side

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/eumetsat-EOWS#310]
On the client side, these layers are not present on the layers list:
- MSG HR 0DEG Channel WV 6.2 (> 3hr) (#249 )
- Copernicus S3B SLSTR L3U SST (#301 )

On the client side, these layers are not visible on map: 
- ~EPS M01 ASCAT Wind BUFR as Shapefile (#223 )~
- Copernicus S3A/B OC4Me CHL Daily (#287 )
- Copernicus S3B OC4Me CHL (#291 )
- Copernicus S3A OC4Me CHL (#284 )

**Comment by Gnafu** [comment]
ASCAT L2 Winds at 12.5 Km - Metop A (along with Metop B and Metop C) are actually visible.
The sample data is west of Mexico
![image](https://user-images.githubusercontent.com/3932165/77053417-9a3ba100-69ce-11ea-9944-0881b2c9819d.png)

**Comment by Gnafu** [comment]
All CHL mosaics show the same issue, not being able to render some of the tiles.
This is related to the colormap styles they are using.

Daniele will help with investigation.

I'm putting a proper example together to reproduce the issue and open a JIRA

**Comment by Gnafu** [comment]
OC4Me CHL issue is tracked here: #312

**Comment by Gnafu** [comment]
OC4Me CHL are now visible.

MSG HR 0DEG Channel WV 6.2 (> 3hr)  is layer msg_fes:wv062 and it is now visible on the layers list.

Copernicus S3B SLSTR L3U SST is layer copernicus:sentinel3b_slstr_l3u_sst_fulres, still missing.

I notified Stefano about that.
