### ISSUE TITLE
Check if JPEG TURBO is actually working

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/eumetsat-EOWS#317]
It should be enabled but in the module list there is a warning sign

**Comment by Gnafu** [comment]
The native library was installed but java did not know where to find it.
Fixed with a change in the Dockerfile

```ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/libjpeg-turbo/lib64```

**Comment by simboss** [comment]
is this avaible on the slaves yet?

**Comment by Gnafu** [comment]
@simboss yes, I did a deploy yesterday.
