### ISSUE TITLE
Mitigate GetTimeSeries issues

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/eumetsat-EOWS#318]
EDIT: Create _histogram layers to mitigate this

Example:
    Request URL: 
    https://view.cgi-dev.de/geoserver/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetTimeSeries&FORMAT=image/vnd.jpeg-png&TRANSPARENT=true&QUERY_LAYERS=copernicus:sentinel3a_slstr_l2p_sst_fullres&LAYERS=copernicus:sentinel3a_slstr_l2p_sst_fullres&STYLES=&tiled=true&&INFO_FORMAT=application/csv&I=292&J=422&WIDTH=512&HEIGHT=512&CRS=EPSG:4326&BBOX=56.25,11.25,67.5,22.5&TIME=2020-02-12T08:38:00.000Z/2020-02-13T08:38:59.999Z&access_token=cdd70139-718d-37a9-bddf-635840f4a260
```
<ServiceExceptionReport xmlns="http://www.opengis.net/ogc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.3.0" xsi:schemaLocation="http://www.opengis.net/ogc https://view.cgi-dev.de/geoserver/schemas/wms/1.3.0/exceptions_1_3_0.xsd?access_token=cdd70139-718d-37a9-bddf-635840f4a260">
<ServiceException>
Error processing the operation org.geotools.util.DateRange cannot be cast to java.util.Date
</ServiceException>
</ServiceExceptionReport>
```
@ElenaGallo please review the client again.

**Comment by Gnafu** [comment]
This turned out to be a bug, see #319

@ElenaGallo Can you please list all the layers that have a non-working timeseries tool enabled in the client?

**Comment by ElenaGallo** [comment]
The error is present in the following data:
- SLSTR Level 2 SST Daily Accumulated - Sentinel-3 
`copernicus:sentinel3a_slstr_l2p_sst_fullres`
- OLCI Level 2 CHL Concentration Daily Accumulated - Sentinel-3 `copernicus:sentinel3b_olci_l2_chl_fullres`
- SLSTR Level 2 Sea Surface Temperature (SST) - Sentinel-3B `copernicus:sentinel3b_slstr_l2p_sst_fullres`
- OLCI Level 2 CHL Concentration - Sentinel-3B
 `copernicus:daily_sentinel3ab_olci_l2_chl_fullres`
- SLSTR Level 2 Sea Surface Temperature (SST) - Sentinel-3A `copernicus:daily_sentinel3ab_slstr_l2p_sst_fullres` 
-

**Comment by Gnafu** [comment]
Thank you.
Assigning to me to mitigate this issue

**Comment by Gnafu** [comment]
Alternative layers created and deployed.
Stefano Marra has been notified for the client configuration change needed to use them.

**Comment by simboss** [comment]
this is done no?

**Comment by Gnafu** [comment]
Done
