### ISSUE TITLE
Install debugging tools in GeoServer containers

### ISSUE THREAD

**Issue by randomorder** [geosolutions-it/eumetsat-EOWS#32]
Some useful debugging tools are currently not available in GeoServer containers, for instance jmap and jstack

**Comment by simboss** [comment]
@randomorder is this still open?

**Comment by randomorder** [comment]
https://github.com/geosolutions-it/docker-gs-base/commit/06ff5dafd9ddba4a29ea93d4cfc15ab0ad65c743
