### ISSUE TITLE
Natural Earth Background artifacts with 3995 projection

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/eumetsat-EOWS#321]
![image.png](https://images.zenhubusercontent.com/5cd44174fe59e12f2130c49d/ab76d40a-237d-4eb2-b4d8-a3f0ba90cfea)

Zooming in, the issue persist.
Tile URL: https://view.cgi-dev.de/geoserver/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fjpeg&TRANSPARENT=true&LAYERS=backgrounds%3Ane_background&STYLES=&tiled=true&WIDTH=512&HEIGHT=512&CRS=EPSG%3A3995&BBOX=-1128800%2C10442400%2C1764000%2C13335200

**Comment by ElenaGallo** [comment]
The issue occurs on Natural Earth background (`backgrounds:ne_background`) in particular on this tile: 

> https://view.cgi-dev.de/geoserver/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fjpeg&TRANSPARENT=true&LAYERS=backgrounds%3Ane_background&STYLES=&tiled=true&WIDTH=512&HEIGHT=512&CRS=EPSG%3A3995&BBOX=-1128800%2C10442400%2C4656800%2C16228000



### Background config:

> /home/geosolutions/geoserver-directories/wms-ns/datadir/workspaces/backgrounds/naturalearth_raster

**Comment by Gnafu** [comment]
@ElenaGallo please attach the data and the configuration here

**Comment by aaime** [comment]
Still investigating the actual cause, but in the meantitime, found a possible workaround, setting the input transparent color to black seems to make the issue disappear:

![image](https://user-images.githubusercontent.com/325433/89278830-e66a4380-d646-11ea-8d17-db55eabe7675.png)

![image](https://user-images.githubusercontent.com/325433/89278898-fd109a80-d646-11ea-8537-090ddac103fe.png)

**Comment by Gnafu** [comment]
Fixed on https://github.com/geosolutions-it/geotools/commits/EOWS-158
