### ISSUE TITLE
Rasters are cut on low zoom levels with Noth Polar Projection

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/eumetsat-EOWS#322]
Metop, Sentinel and MSG - 0 Degree data are seen on the map with the cut parts that disappear when you zoom in on them:
![SI](https://user-images.githubusercontent.com/56537133/77894825-23c45c00-7276-11ea-92c2-a60ad69a07b1.gif)

These are the cut parts:
![SI2.JPG](https://images.zenhubusercontent.com/5da5b30f66de7b0001e4e77c/e49f0eeb-8bfb-41c7-b9c6-2e1af36b7a53)

**Comment by Gnafu** [comment]
@ElenaGallo are you able to reproduce this issue locally?
Can you please prepare a package with a data sample and the configuration to reproduce this issue?

**Comment by ElenaGallo** [comment]
This issue only occurs in North Polar Projection on the client side. One of the layer affected by this issue is AVHRR RGB Natural Colour + Fog 6 orbits accumulated - Metop B ( `eps:m01_rgb_natural_fog`) in particular on these tiles: 

> https://view.cgi-dev.de/geoserver/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fvnd.jpeg-png&TRANSPARENT=true&LAYERS=eps%3Am01_rgb_natural_fog&STYLES=&tiled=true&TIME=2020-02-17T05%3A16%3A00.000Z&WIDTH=512&HEIGHT=512&CRS=EPSG%3A3995&BBOX=-1128800%2C-12700000%2C10442400%2C-1128800&access_token=55f4faff-48a8-30db-956d-430fd89b8d6d

> https://view.cgi-dev.de/geoserver/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fvnd.jpeg-png&TRANSPARENT=true&LAYERS=eps%3Am01_rgb_natural_fog&STYLES=&tiled=true&TIME=2020-02-17T05%3A16%3A00.000Z&WIDTH=512&HEIGHT=512&CRS=EPSG%3A3995&BBOX=-12700000%2C-1128800%2C-1128800%2C10442400&access_token=55f4faff-48a8-30db-956d-430fd89b8d6d

### Mosaic config:

The configuration folders are available [here](https://drive.google.com/drive/folders/1gsQ1DRf-wa6Ahjk7sg6sGQNrm1QiRUhz?usp=sharing) ( used GeoSerever 2.16-SNAPSHOT )

The granules affected are located on sftp://guest@files.eumetsat.int (for the password contact us)  in this folder:
> /wms_pilot_demo/metop1_natural_fog

**Comment by Gnafu** [comment]
Fixed on https://github.com/geosolutions-it/geotools/commits/EOWS-158
