### ISSUE TITLE
Dateline crossing layers artifacts on reprojection

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/eumetsat-EOWS#323]
![4](https://user-images.githubusercontent.com/56537133/75872842-2f576b00-5e0f-11ea-865a-dd95d3674997.JPG)

Found on #290

Samples are 1.4GB each.
I'm still trying to reproduce this locally.

**Comment by ElenaGallo** [comment]
The issue occurs on OLCI Level 1B RGB Daily Accumulated - Sentinel-3 
( `copernicus:daily_sentinel3ab_olci_l1_rgb_fulres`) in particular with granule:
- oclil1_s3ab_accu_daily_rgb_2002140019_2002141708.tif

On this tile: 

> http://localhost:8080/geoserver/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fvnd.jpeg-png&TRANSPARENT=true&LAYERS=copernicus%3Adaily_sentinel3ab_olci_l1_rgb_fulres&STYLES=&tiled=true&TIME=2020-02-14T17%3A08%3A00.000Z&WIDTH=512&HEIGHT=512&CRS=EPSG%3A4326&BBOX=-90%2C-180%2C0%2C-90&access_token=b82d51f7-5dcd-368a-9495-f77d8fef2691

- oclil1_s3ab_accu_daily_rgb_2002140019_2002141929.tif

On this tile: 

>http://localhost:8080/geoserver/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fvnd.jpeg-png&TRANSPARENT=true&LAYERS=copernicus%3Adaily_sentinel3ab_olci_l1_rgb_fulres&STYLES=&tiled=true&TIME=2020-02-14T19%3A29%3A00.000Z&WIDTH=512&HEIGHT=512&CRS=EPSG%3A4326&BBOX=-90%2C-180%2C0%2C-90&access_token=b82d51f7-5dcd-368a-9495-f77d8fef2691

**Comment by Gnafu** [comment]
@ElenaGallo please create a zip file with the mosaic configuration and attach it here

**Comment by aaime** [comment]
I got the configuration files from google drive, thanks. Where do I get the actual data?

**Comment by simboss** [comment]
sftp above, ask me or lorenzo the pwd

**Comment by aaime** [comment]
For my own reference, GetMap showing the problem:

```
/geoserver/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fvnd.jpeg-png&TRANSPARENT=true&LAYERS=copernicus%3Adaily_sentinel3ab_olci_l1_rgb_fulres&STYLES=&tiled=true&TIME=2020-02-14T17%3A08%3A00.000Z&WIDTH=512&HEIGHT=512&CRS=EPSG%3A4326&BBOX=0%2C-180%2C90%2C-90
```

**Comment by aaime** [comment]
Should be fixed too. There is no change in the EOWS branch, because the issue had to be solved in GeoTools instead: 
https://osgeo-org.atlassian.net/browse/GEOT-6543

(the ticket does not directly talks about black borders, but about the changes that happens to make them disappear, which was already present on master due to a completely unrelated reason...).

Long story short, as long as you use an up to date version of 22.x for the build, it should be fine.

**Comment by simboss** [comment]
@aaime I think we fixed also the GeoTools branch to match the GeoServer branch, hence we might need a cherry pick.

@Gnafu can yo confirm?

**Comment by aaime** [comment]
@simboss I don't see a EOWS branch here: https://github.com/geosolutions-it/geotools

**Comment by simboss** [comment]
@Gnafu ?

**Comment by Gnafu** [comment]
The geotools branch still needs to be locked, there's a pending issue for this: https://github.com/geosolutions-it/eumetsat-EOWS/issues/295

**Comment by Gnafu** [comment]
Confirmed working on "geoserver-dev" environment
https://geoserver-dev.cgi-dev.de/geoserver/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=copernicus%3Adaily_sentinel3ab_olci_l1_rgb_fulres&STYLES=&tiled=false&TIME=2020-02-14T17%3A08%3A00.000Z&WIDTH=512&HEIGHT=512&CRS=EPSG%3A4326&BBOX=-90%2C-180%2C0%2C-90

For comparison the "dev" one that has not been updated:
https://view.cgi-dev.de/geoserver/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=copernicus%3Adaily_sentinel3ab_olci_l1_rgb_fulres&STYLES=&tiled=false&TIME=2020-02-14T17%3A08%3A00.000Z&WIDTH=512&HEIGHT=512&CRS=EPSG%3A4326&BBOX=-90%2C-180%2C0%2C-90
