### ISSUE TITLE
Create generic Docker Images for GeoServer

### ISSUE THREAD

**Issue by randomorder** [geosolutions-it/eumetsat-EOWS#33]
Would be nice to have a generic, ready to use, Docker Image for GeoServer with following characteristics:
- [ ] standard set of plugins: Controlflow, Monitor, Status Monitoring
- [ ] 3 "flavours" (tags) of images that follow GeoServer release cycle, for instance unstable, stable, maintenance. For instance at the time of writing would mean an "unstable" image with GeoServer 2.12 , a "stable" with 2.11 and a "maintenance" with 2.10

**Comment by simboss** [comment]
@randomorder is this still open?

**Comment by randomorder** [comment]
github.com/geosolutions-it/docker-geoserver
