### ISSUE TITLE
Assorted Importer Issues

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/eumetsat-EOWS#330]
A collection of issues we faced during the use of the importer

**Comment by simboss** [comment]
@nmco I think we can assign this to @taba90

**Comment by nmco** [comment]
Understood @simboss.

**Comment by simboss** [comment]
@nmco @taba90 all these issues shall be backported up to 2.16.x and then cherrypicked to eumetsat.

@taba90 make sure the EUM branch builds and tests pass everytime you backport something to it. @
