### ISSUE TITLE
GEOS-8665 - Cannot import if the layer name equals the native name

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/eumetsat-EOWS#332]
JIRA: https://osgeo-org.atlassian.net/browse/GEOS-8665

**Comment by nmco** [comment]
@taba90 can you investigate and propose an estimate?

**Comment by taba90** [comment]
I would need some more informations to reproduced this. I tried to reproduce the issue partially following examples example in the section [Uploading a CSV file to PostGIS while transforming it ](https://docs.geoserver.org/maintain/en/user/extensions/importer/rest_examples.html). Basically I've proceeded as follows:

-create a void import with http://localhost:8080/geoserver/rest/imports
-create a task to upload new records to a postgis table from a csv file eg: `curl -u admin:geoserver -F name=test -F filedata=@values.csv "http://localhost:8080/geoserver/rest/imports/0/tasks"`

- did a put http://localhost:8080/geoserver/rest/imports/3/tasks/1/layer with this body 

> {
  "task": {
     "updateMode": "APPEND",
     "layer": {
    "name": "test",
    "nativeName": "test",
    "srs": "EPSG:4326"
  }
  }
}

- EPSG got updated in the tasks and running the import with the post will update the postgis table

- Some endpoints in [this doc page](https://docs.geoserver.org/maintain/en/user/extensions/importer/rest_examples.html) seem wrong and should be updated

**Comment by nmco** [comment]
@Gnafu can have a look at @taba90 feedback? Maybe we are missing some step to be able to reproduce this.

**Comment by Gnafu** [comment]
@taba90 try uploading a shapefile instead of a csv.
If that works, this might be already fixed between 2.14.x and 2.16.x

**Comment by taba90** [comment]
@Gnafu the issue didn't get reproduced also for shapefile. I've followed the [Uploading a shapefile to Postgis example](url) adding the step highlighted in the the JIRA ticket

**Comment by Gnafu** [comment]
Thank you.
Closing this as non-reproducible.
