### ISSUE TITLE
Review reported issues on OPE

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/eumetsat-EOWS#336]
From Kiril:

[IMGMT-295 WMS: Ingestion failed for Metop RGB 124](https://cgi-pathfinders.atlassian.net/browse/IMGMT-295)

For this I think you are already in contact with ASK and know what the issue is about.

[IMGMT-286 WMS: Download and color scales](https://cgi-pathfinders.atlassian.net/browse/IMGMT-286)

Here I am not sure if you are the right person. The problem is that the full resolution download of GeoTiffs produces a zip file with a greyscale image and some additional color information files. EUM expected to have a color graded image instead. The PNG download produces an error.

[IMGMT-284WMS: The download size is too big](https://cgi-pathfinders.atlassian.net/browse/IMGMT-284)

Please increase the download size limit to 2GB.

**Comment by simboss** [comment]
this is a top priority @Gnafu 


keep me posted..

**Comment by Gnafu** [comment]
IMGMT-295 occurred on DEV, a restart fixed the issue.
Issue for a post-mortem: #337

**Comment by randomorder** [comment]
all issues in the EPIC are closed. Closing the EPIC as well
