### ISSUE TITLE
Review Memory Dump for stuck Master instance

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/eumetsat-EOWS#337]
The docker container was up and tomcat responding 404 to any request for GeoServer

The GeoServer image used is 
```docker-pullable://harbor.cgi-dev.de/geoserver/geoserver@sha256:1a3efc41ee5aaaea4ebefa57445537bc457972233ce8cfe2cc092f29c2040a48```

GeoServer was built from this tag:
https://github.com/geosolutions-it/geoserver/tree/WMS-1-0

with the following profiles:
-Pauthkey -Pcontrol-flow -Pcss -Pfeature-pregeneralized -Pimporter -Plibjpeg-turbo -Pmonitor -Pnetcdf -Pnetcdf-out -Pwps -Pimporter-jdbc -Pncwms -Pghrsst -Pwmts-multi-dimensional -Pwps-download -Pwps-jdbc

Post Mortem package: 
https://www.dropbox.com/s/yvo9zmxjgymzr9f/20200515_geoserver_master_dev_NPE.7z?dl=0

In the package you can find:
- Logs
- Jmap
- Jstack
- environment variables

**Comment by Gnafu** [comment]
@simboss this will need a GeoServer developer to have a look.

**Comment by simboss** [comment]
@aaime can you give this a quick look when you have time?

**Comment by randomorder** [comment]
still relevant? It is linked to [epic 336](https://github.com/geosolutions-it/eumetsat-EOWS/issues/336)

**Comment by simboss** [comment]
let's kill it for the moment
