### ISSUE TITLE
Estimate for implementing Equi7Grid in GeoServer

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/eumetsat-EOWS#340]
There is sparse documentation around but I would start from [this](https://cartography.tuwien.ac.at/eurocarto/wp-content/uploads/2015/09/3_6_ppt.pdf) presentation.

I am also trying to gather additional information, which I will report here.

**Comment by simboss** [comment]
Maybe first a little background. The Data Store UI (e.g. https://data.eumetsat.int/data/map/EO:EUM:DAT:METOP:IASSND02) provides a feature to narrow down the search using a spatial filter. Either bounding box or the Equi7Grid-based filters are supported. Each product is indexed to the intersecting tiles of E7G upon ingestion.

Now in order to provide a good experience to the user, the Data Store UI displays each E7G region in its specific projected CRS. OpenLayers comes with an on-the-fly raster reprojection, but that obviously fails in extremity regions such as the Antarctic or Northern America. You can try it out by navigating to the NA region, there is a base layer mirroring effect appearing.

I did some prototyping to overcome this issue with dedicated layers in a local Geoserver instance. I set up 7 data stores and layers as WMS, each with a GeoTIFF in the specific E7G CRS as the data source. So I guess what you need to do is to reproject the current baselayer data source to the 7 CRS (definitions are available [here](https://github.com/TUW-GEO/Equi7Grid/blob/master/equi7grid/grids/AF/PROJ/EQUI7_V13_AF_PROJ_LAND.prj)) and set up a dedicated workspace with the 7 layers accordingly. The data sources could also be limited to the extent of the corresponding E7G region.

Let me know if this helps or if we should set up a brief call.

Best
Matthes

**Comment by simboss** [comment]
@aaime I would estimate a proper implementation in GeoServer.

**Comment by aaime** [comment]
Checked the documentation, presentations and code repository. This Equi7Grid system does not look like a projection to me, it's actually 7 separate AzimuthalEquidistant to be applied in 7 different areas in the world.

This folder in the repository contains the 7 zones and shapefiles projected in the zone associated projection:

https://github.com/TUW-GEO/Equi7Grid/tree/master/equi7grid/grids

One can run ogrinfo to get the projection definition:

```
ogrinfo -al -so AF/PROJ/EQUI7_V13_AF_PROJ_ZONE.shp
INFO: Open of `AF/PROJ/EQUI7_V13_AF_PROJ_ZONE.shp'
      using driver `ESRI Shapefile' successful.

Layer name: EQUI7_V13_AF_PROJ_ZONE
Metadata:
  DBF_DATE_LAST_UPDATE=2015-02-24
Geometry: Polygon
Feature Count: 1
Extent: (-0.000004, 0.000001) - (11480904.712678, 9364439.712267)
Layer SRS WKT:
PROJCS["equi7_africa_nofalseXY",
    GEOGCS["GCS_WGS_1984",
        DATUM["WGS_1984",
            SPHEROID["WGS_84",6378137.0,298.257223563]],
        PRIMEM["Greenwich",0.0],
        UNIT["Degree",0.0174532925199433]],
    PROJECTION["Azimuthal_Equidistant"],
    PARAMETER["false_easting",5621452.01998],
    PARAMETER["false_northing",5990638.42298],
    PARAMETER["longitude_of_center",21.5],
    PARAMETER["latitude_of_center",8.5],
    UNIT["Meter",1.0]]
GRID: String (20.0)
VERSION: String (10.0)
ZONE: String (20.0)
SHORTNAME: String (20.0)
```

As far as I can tell, to reproject the rasters on the server side one needs to setup these 7 new codes as user projections, and have the client call onto them when displaying the map of one of the 7 areas.

To confirm that they are not meant to be a single continous projection, I've used the shapefiles to lookup the position of Gibraltar in the maps of Europe and Africa. In Europe it's roughty at 3M,700k, while in the African one it's at 3M,9M. The Y delta is huge.

The Azimuthal Equiditant projection is supported by GeoServer and has a projection handler.
Did a quick test using BlueMarble with the European area. The output from Eumetsat client side reprojection for reference, with the mirror effect they were talking about:

![image](https://user-images.githubusercontent.com/325433/84032735-0d363180-a998-11ea-8b30-567bb5ffb4d4.png)

and the one from GeoServer:

![image](https://user-images.githubusercontent.com/325433/84032782-1fb06b00-a998-11ea-9668-f01548595951.png)

The only note I have is that the output is slow, generating the above image (WIDTH=768&HEIGHT=672) took 1.7 seconds. The input file has overviews.

I would recommend trying out all 7 projections to make sure everything works before sharing an estimate ;-). Do you want me to do it?

**Comment by simboss** [comment]
I will ping you later.

**Comment by aaime** [comment]
Africa:

![image](https://user-images.githubusercontent.com/325433/84041118-c0f0ee80-a9a3-11ea-820e-ef6c9dea87b8.png)

Antarctica:

![image](https://user-images.githubusercontent.com/325433/84041175-ccdcb080-a9a3-11ea-8bd5-b1d25ef2828c.png)

Asia:
![image](https://user-images.githubusercontent.com/325433/84041273-e7168e80-a9a3-11ea-8fa7-6bcc10fe9c0a.png)

North america:
![image](https://user-images.githubusercontent.com/325433/84041341-01506c80-a9a4-11ea-8d09-4c1fd880c987.png)

Oceania:
![image](https://user-images.githubusercontent.com/325433/84041389-10371f00-a9a4-11ea-9b68-0811d139ae30.png)

South america:
![image](https://user-images.githubusercontent.com/325433/84041649-5f7d4f80-a9a4-11ea-9614-776080907d1c.png)

Raster cutting is a bit aggressive in some, I suggest we dedicate some time investigating and improving, also, we discussed ideas to improve performance of reprojection:
- 2 days to improve the projection handler
- (optional) 6 days to work a better piece-wise reprojection that would leverage overviews better, rather than reading the resolution needed by the area with the worst deformation

**Comment by simboss** [comment]
thx
