### ISSUE TITLE
IMGMT-341 Wrong colour scale SLSTR Level 3 Uncollated Sea Surface Temperature (L3U SST)

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/eumetsat-EOWS#343]
SLSTR Level 3 Uncollated Sea Surface Temperature (L3U SST) (both 3B and 3A) seems to have a different colour scale compared to SLSTR Level 2P, but the legends displayed in the product settings are all the same.

@simboss @randomorder this might be just a configuration issue, but I need to check to be sure.

**Comment by randomorder** [comment]
ok, check the style. It should be a quick thing to do

**Comment by Gnafu** [comment]
Indeed sentinel3a_slstr_l2p_sst_fullres is using sst_medspiration_single_band style
while sentinel3a_slstr_l3u_sst_fulres is using sst_composition3

This is because the sentinel3a_slstr_l3u_sst_fulres  styles where never defined by eumetsat specification https://drive.google.com/file/d/1jQGIx9McccrJv4ennlrVBc2tf4MUk0g0/view?usp=sharing
it is listed as "Palette: TBD"

**Comment by randomorder** [comment]
What are the next steps? You providing the style? How long will it take? Please add an estimate

**Comment by Gnafu** [comment]
- set sentinel3a_slstr_l3u_sst_fulres  to use sst_medspiration_single_band 
- check it looks fine
- apply to production master (OPE)
- Ask Nicolas Morew for a new deploy on OPE

Then, if the deploy pipeline on OPE is not set yet
- Change the authkey settings on DEV to match OPE
- Trigger DEV pipeline
- Retag the image as OPE
- Send the image tag to Nicolas
- Revert the authkey settings on DEV

Changes and tests take a few minutes.
The longest part is the deploy.

**Comment by Gnafu** [comment]
Deployed on OPE

**Comment by Gnafu** [comment]
Confirmed by Ilaria Parodi
