### ISSUE TITLE
COG: make a status check and a plan of activities

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/eumetsat-EOWS#345]
The goal of this issue is to check exactly where we are with COG support for GeoTiff and ImageMosaic/ImagePyramid wrt the work that @aaime and Josh Fix did so far.

The outcome is a plan with relateive issue and ballparks estimates that we can act upon right aftewards as we want to complete COG support asap.

**Comment by dromagnoli** [comment]
Initial document with notes and findings have been setup:
https://docs.google.com/document/d/1t2EUh38RezOhOpHubVz5nZ7OhiTHRgW4upNVdb_dPvI/edit#heading=h.yaaoxu1azhsw

**Comment by dromagnoli** [comment]
Tickets have been created on the epic:
https://github.com/geosolutions-it/support/issues/750
