### ISSUE TITLE
Improvements the projection handler

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/eumetsat-EOWS#352]
Citing @aaime email ""

> Raster cutting is a bit aggressive in some cases so we see some white lines, we suggest we dedicate some time investigating and improving, also, we discuss ideas to improve performance of reprojection.

This is probably related to #321 and  #322 

We shall pay attention to the geoserver version that EUM is using as I don't think we can afford a complete upgrade just for this fix.

**Comment by simboss** [comment]
@aaime make sure you provide some status on the issue when you are done with the work.
This will be the input for Lorenzo when he comes back.

**Comment by aaime** [comment]
Both referenced issues have been solved and the fixes backported to the EOWS-158 branches.
Tested the data with the branch in question, here are a few screenshots from a tiled preview:

![image](https://user-images.githubusercontent.com/325433/89522585-befbae00-d7e1-11ea-9b25-33031349e0aa.png)

![image](https://user-images.githubusercontent.com/325433/89522595-c1f69e80-d7e1-11ea-9e9a-761b70bb2ff5.png)

The tiny white line in the top map is actually in the data itself, can be seens without any reprojection:

![image](https://user-images.githubusercontent.com/325433/89522717-f66a5a80-d7e1-11ea-9e34-11e212d13cf1.png)

Also looking at Natural Earth, screenshots from a tiled preview follow:

![image](https://user-images.githubusercontent.com/325433/89522859-2f0a3400-d7e2-11ea-8aa0-e258a85cfe7c.png)

![image](https://user-images.githubusercontent.com/325433/89522876-3b8e8c80-d7e2-11ea-92a9-cff677228298.png)

**Comment by Gnafu** [comment]
Moving this to complete because:
- It has been tested by @aaime 
- There is another issue #353 to test this on Eumetsat environment

**Comment by Gnafu** [comment]
@aaime the branches you are referring to are these ?
https://github.com/geosolutions-it/geotools/tree/EOWS-158
https://github.com/geosolutions-it/geoserver/tree/EOWS-158

**Comment by aaime** [comment]
Yes. I believe the changes needed actually landed only in GeoTools. Ah, I forgot to push them, done so now:

![image](https://user-images.githubusercontent.com/325433/90402457-c2275180-e09f-11ea-828f-3c9dc69f9fc2.png)

**Comment by Gnafu** [comment]
Thank you.
I see this issue is related to the "Equi7Grid implementation and deployment" #346 
Is this the implementation? Or is there another issue/branch for that?

**Comment by aaime** [comment]
Well yes, #346 points indeed at this one as the first step:

![image](https://user-images.githubusercontent.com/325433/90405911-b8541d00-e0a4-11ea-89df-379b66022cc3.png)
