### ISSUE TITLE
Test, deploy and configuration in GeoServer

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/eumetsat-EOWS#353]
Test and deploy fixes for GeoServer.

Let's decide if we do a patch or if we do a release.

**Comment by Gnafu** [comment]
Reminder for me: Add a deploy diagram to the doc if it is missing.

**Comment by simboss** [comment]
@Gnafu apparently @aaime is almost done with his work.
He should have cherrypicked things to the EUM fork and tested it already.

This is your top priority for the 17th together with [this one](https://github.com/geosolutions-it/eumetsat-EOWS/issues/354)

**Comment by Gnafu** [comment]
Build went fine. Going to deploy on dev for testing

**Comment by Gnafu** [comment]
During the deploy I found 2 possibly unrelated (and existing) issues:

- If the "Enable automatic densification of geometries" is enabled, reprojection fails with "Error transforming bbox"
- Adding the epgs.properties file with the custom projections definitions requires to specify the 900913 in the file as well, or it will no longer be recognized as a valid epsg code

**Comment by aaime** [comment]
The 900913 part is a given, has always been like that, it's not a code that is present either in the EPSG database, nor in the code itself, so it has to be there. 

About densification, I don't know about it, is it ok to just keep it off for the project? Otherwise we'll need a separate issue with steps to reproduce.

**Comment by Gnafu** [comment]
We enabled densification to fix some glitches in 3995 reprojections
One option can be to temporarily disable it while we fix the issue

**Comment by randomorder** [comment]
waiting for feedback from Matthes on the gridset to use

**Comment by randomorder** [comment]
caching is working. CGI is discussing w/ Matthes about some changes to the client application but our work is in
