### ISSUE TITLE
IMGMT-370 - Investigate OOM Error during animation generation

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/eumetsat-EOWS#357]
They are experiencing an OOM when working with animations.

The initial exchange is [here](https://docs.google.com/document/d/1-33Zhn0NEfkAEcaHACP_BJKjMQX6L_-EJy3kNX7hmBM/edit?usp=sharing) we shall try to replicate and then ask one of our developers to have a look.

**Comment by randomorder** [comment]
JIRA issue [here](https://cgi-pathfinders.atlassian.net/browse/IMGMT-370)

Memory dumps at `ftp.geo-solutions.it` login as user `cgi` password [here](https://docs.google.com/spreadsheets/d/16PuEm75Pn6OInFKwqMLEFUDGdCT0Kw23a9dEtFGkV0I/edit#gid=0)

**Comment by aaime** [comment]
Anything more to do here? Investitation done and mitigations are in place

**Comment by simboss** [comment]
done, thx
