### ISSUE TITLE
Configure TIME parameter in the Tile Caching option when needed

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/eumetsat-EOWS#36]
We have a number of layers with the TIME dimension enabled on the CloudSDI server as well as on the Hetzner port (talk to Alessandro for getting access to this).

We need to configure Tile Caching to handle the TIME parameter properly; The configuration is as follows:
- set up a invalid  value for the default TIME value disallow caching which allows us to always see the latest without problems when specifying no TIME dimension value from the client
- use the following regular expression to capture valid time expressed according to the ISO 8601 syntax ^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}.\d{3}Z$

**Comment by randomorder** [comment]
TIME parameter configured. We should decide how to handle requests without TIME parameter, see #38
