### ISSUE TITLE
[AOB X] Set up PostgreSQL HA 

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/eumetsat-EOWS#364]
From the client.

`At the moment, GeoServer is using a single instance of Postgres DB. Redundancy between at least 2 instances (either prime-backup or synchronized instances) should be foreseen for the operational phase.`

We have to come up with options on how to achieve this requirement and estimate.

We need this rather quickly, @randomorder let's ask help from Luca!

**Comment by randomorder** [comment]
PostgreSQL is deployed as part of a big Helm Chart for the "wms" namespace in K8s comprising the following subcharts
![image](https://user-images.githubusercontent.com/5264230/91870564-4b7d7d00-ec77-11ea-9bad-4d3050a82c8e.png)

I am assuming:
- the Helm Charts [here](https://gitlab.cgi-dev.de/eows/wms/wms-cicd/tree/master/charts/wms/charts/postgres-wms-geoserver) are still valid and working and updated (I don't think they are) 
- deployment would be pretty much flawless (but we'll probably need more grants or CGI's help for the deployment or both).

Current Chart for postgres written very poorly with passwords in clear text and default configuration is use for postgres which is not ok, especially for a big prod system like Eumetsat's.

We're on PostgreSQL version 9.6.12 / PostGIS 2.5. PostgreSQL

Data directory is 139GB in size, PG stats show smaller numbers. Not a huge amount of data anyway
![image](https://user-images.githubusercontent.com/5264230/91869628-68658080-ec76-11ea-9e24-a8a1051c8034.png)
![image](https://user-images.githubusercontent.com/5264230/91870022-d1e58f00-ec76-11ea-80d2-f785269d36ea.png)

BTW, do you know how long are we going to keep the data in the database @simboss ? For "m01_ascat_wind" for instance I've got 
![image](https://user-images.githubusercontent.com/5264230/91872189-e0807600-ec77-11ea-8bdb-73207d8170f5.png)

Some of the options available:
1 - https://bitnami.com/stack/postgresql-ha/helm
2 - https://portworx.com/ha-postgresql-kubernetes/
3 - https://access.crunchydata.com/documentation/postgres-operator/latest/
4 -  something else

From my first impressions, I like #1 and #3 we need to dig a little deeper to understand pros / cons of each solution. Note that what we want at the moment is:
- HA, not necessarily better performance
- Possibly monitoring of the health and performance of the cluster or an easy way to integrate with an existing monitoring solution
- A way to administer the cluster


Whatever solution we go for we'll have to:
- integrate it into the Helm Charts (I'll double check with CGI they are still using the Charts)
- make sure the docker image includes the postgis extension or we have a way to customize the docker image to add postgis to it.
- migrate the data from the existing postgresql installation (likely older version)

My guesstimate is: 
- 1 days for investigation
- 1,5 days for local testing / building the docker image
- 1,5 day for testing /deploying in DEV
- 1 day for data migration and deploymend in OPE
= 5 days @simboss

**Comment by randomorder** [comment]
Estimation done. Closing, please re-open as needed

**Comment by randomorder** [comment]
@lpasquali your thoughs with a  drafted proposal and an estimate before moving on with the implementation please

**Comment by lpasquali** [comment]
after the tests on my small kubernetes testing environment:
- portworks is not suitable for non-cloud k8s.
- bitnami postgres implementation supports ha and it is easy to implement (works out of the box for helm2) -> deleting one pod of two in HA results for the psql client to not connect anymore until the deleted pod has been scheduled but maybe the psql client is not comparable to JNDI or the native connection pooling of geoserver and I would like to test against it. Postgis extensions were present out of the box, tested a postgres 12, connection to postgres is not secure.
- zalando (https://github.com/zalando/postgres-operator/blob/master/docs/quickstart.md) is cool but I'm unsure it is the best fit (very configurable but needs testing and it is quite complicated, it has helm charts but from my first tries they do not work out of the box and client has old versions of helm right now) this one is for scaling master/slave instances of postgres ha reliability can be achieved dedicating each postgres replica to a node if read-only nodes are enough for geoserver (with obvious exceptions for quota on db) but it is not an HA implementation, Postgis extensions were present out of the box, tested a postgres 12, the connection is secure on ssl by default.
- there is also: https://operatorhub.io/operator/postgresql-operator (only read about, installed, not tested, very alpha)
- and also: https://operatorhub.io/operator/postgresql-operator-dev4devs-com (only read about, might be worth to look)
- why not  https://access.crunchydata.com/documentation/postgres-operator/latest/: because it needs a specific client to ingest kubectl config and drastically changes the way of managing things on a k8s cluster (due to this particular cli) which may vbe difficult to be appreciated our customer.

**Comment by lpasquali** [comment]
I tested deeply bitnami and zalando implementation against version 1.15.12 of kubernetes.
on the scalability point of view they are moree or less equal even if the zalando solution looks a bit faster reloading a failed postgres pod.

the gui in zalando is what makes such solution betterly manageable and monitorable, backups, cloned clusters, can be done in a few clicks.
zalando supports ssl for us (and looks like to be working in geoserver both as store and diskqouta db)
zalando project is totally based on github and it's easy to open and track issues for us.

on both databases it was possible to import data as [this](https://www2.census.gov/geo/tiger/GENZ2017/shp/cb_2017_us_state_20m.zip
) with postgis specific tools like:
`shp2pgsql -I -s 4269 ./cb_2017_us_state_20m.shp public.us_state_20 | psql -U postgres -h localhost geodata
`

**Comment by lpasquali** [comment]
reminder:

- prepare diagram for modifiaction of the infrastructyre
- non-technical deployment of proposed soultion
- non technical lplan for database migration (maybe optional)

**Comment by simboss** [comment]
Migrating the DB is not optional @lpasquali, I believe it is crucial!

@randomorder what do you think?

**Comment by randomorder** [comment]
I was not 100% sure, now I am :) . Shouldn't be a problem make it non optional @lpasquali

**Comment by lpasquali** [comment]
@simboss @randomorder not a problem for me, made not optional :-)

**Comment by lpasquali** [comment]
Planning with graph about I'd implement this solution @randomorder:
https://docs.google.com/document/d/1BF3IqpgymfeTCjtsBkCyQ5C7WFVuFdO12FMiVJGiWCE/edit#

**Comment by randomorder** [comment]
please check my comments in the doc
furthermore:
- is Postgis included out of the box?
- how do we monitor and administer the cluster?
- what kind of postgresql clustering is it / are supported?

**Comment by lpasquali** [comment]
> please check my comments in the doc
> furthermore:
> 
> * is Postgis included out of the box?
yup I tested any possible solutrion against postgres for diskquota and postgis for geospatial data (see my comments above about how  I was importing geospatial data with postgis tools to validate the postgis part.

> * how do we monitor and administer the cluster?
Prometheus
> * what kind of postgresql clustering is it / are supported?
HA administered by patroni, with two nodes, Patroni elects the node without "master lock if master goes down" and updates the service accordigly to serve master from new node.

> * what postgresql / posgis versions are available?
any / any

**Comment by lpasquali** [comment]
@randomorder documentation updated

**Comment by randomorder** [comment]
what  kind of replication is this based on @lpasquali ?

is multi-master cluster supported ?

**Comment by lpasquali** [comment]
Spilo is the docker image which implements HA: https://github.com/zalando/spilo
dat for HA is replicated with Patroni which is bundled in the spilo docker image.

there is no multi-master support: https://github.com/zalando/patroni/issues/673

**Comment by randomorder** [comment]
> Spilo is the docker image which implements HA: https://github.com/zalando/spilo
> dat for HA is replicated with Patroni which is bundled in the spilo docker image.

Didn't actually answered to my question
Synchronous vs Asynchronous -- Logical vs Physical -- WAL based?

**Comment by lpasquali** [comment]
> > Spilo is the docker image which implements HA: https://github.com/zalando/spilo
> > dat for HA is replicated with Patroni which is bundled in the spilo docker image.
> 
> Didn't actually answered to my question
> Synchronous vs Asynchronous -- Logical vs Physical -- WAL based?

it is Patroni based, which syncs configuration and data, it's actually none of the above.

**Comment by randomorder** [comment]
> Anyway it is "somehow" synchronous with "somehow" because it is not same technology.

Ok. doesn't help deciding on whether or not Zalando Operator is a viable solution. Also IF they implemented 
a custom replication mechanism (unlikely) is not looking good in my eyes..

We only use solutions that we understand and, to a degree, know how to manage and debug. Remember
that if something goes wrong our client will blame us, not Zalando and the responsibility of fixing the system will be on us.

**Comment by lpasquali** [comment]
> > Anyway it is "somehow" synchronous with "somehow" because it is not same technology.
> 
> Ok. doesn't help deciding on whether or not Zalando Operator is a viable solution. Also IF they implemented
> a custom replication mechanism (unlikely) is not looking good in my eyes..
> 
> We only use solutions that we understand and, to a degree, know how to manage and debug. Remember
> that if something goes wrong our client will blame us, not Zalando and the responsibility of fixing the system will be on us.

from this fosdem presentation I think they use streaming replication

https://archive.fosdem.org/2020/schedule/event/postgresql_postgresql_on_k8s_at_zalando_two_years_in_production/attachments/slides/3883/export/events/attachments/postgresql_postgresql_on_k8s_at_zalando_two_years_in_production/slides/3883/PostgreSQL_on_K8s_at_Zalando_Two_years_in_production.pdf

https://wiki.postgresql.org/wiki/Streaming_Replication

**Comment by randomorder** [comment]
Technical note [here](https://docs.google.com/document/d/1KOG3FEDRoYlQ7dJMSMhdvAd0cCR9CD243VSyNUugr54/edit) @lpasquali

**Comment by lpasquali** [comment]
- deploy operator
- deploy ui
- check operator from ui
- define cluster manifest (affinity/antiaffinity, node labels, pv size in the pvc, databases + roles)
- deploy cluster manifest (ui or cli, indifferent, afaik is not possble with helm directly)
- migrate databases from old cluster
- rollout other applications with new database endpoint

**Comment by randomorder** [comment]
remember to document these steps @lpasquali

**Comment by lpasquali** [comment]
@randomorder not a big success our test run, but besides I was not able to see any effect on slaves, I got the master working. 
the logic which needed to be added to satisfy pre-existent passwords and to disable ssl added some complication and now the operator has problems with postgres password, but I think I can fix that, it is probably a character which gets intepretated in bash

**Comment by lpasquali** [comment]
@randomorder starting to build up a new cluster so we hopefully can test both on master and slaves with pipelines

**Comment by lpasquali** [comment]
looks like that deployment+ migration of data + deployment of geoserver master and slave were successful now that the CI was restored from CGI

**Comment by randomorder** [comment]
Deployment tested in DEV. Please revert to avoid breaking VAL and OPE now @lpasquali

**Comment by lpasquali** [comment]
@randomorder rolled back

**Comment by randomorder** [comment]
ETA to have this in production is mid January. Anything left to do / to validate on our side? Are we ready to move to VAL?

We can re-enable the cluster in DEV if we need to.

**Comment by randomorder** [comment]
moving to test

**Comment by lpasquali** [comment]
@randomorder 

after what you correctly appointed as a wrong test to CGI which suddently deleted both the two pg cluster pods at same time, (one could do it with three node with no harm, but this is not an option) the pgdata of the cluster supposed to be replica, didn't start because its data was broken, as soon as I renamed its pgroot as pgroot-backup (I actually could have deleted but I preferred to stash it for eventual future analysis) that node was felt as an empty node and a complete sync from the running leader was done.
Everything is back on track.
Probably the problematic pod was deleted while syncing with the leader postgres pod resulting in an unstable set of data.

**Comment by randomorder** [comment]
we want to provide a way to monitor health status of the PG instances @lpasquali so that they can find out when something is wrong

**Comment by lpasquali** [comment]
> we want to provide a way to monitor health status of the PG instances @lpasquali so that they can find out when something is wrong

@randomorder update to align this issue: we provided updated operations manual with a way to monitor PG health

**Comment by randomorder** [comment]
PG HA deployed and validated in VAL

**Comment by lpasquali** [comment]
Installation manual sshould be updated at the point of helm install:
```
@Luca Pasquali the command would be (from the root of the helm-charts repository):

helm upgrade --install <release-name> . --values values-<env>.yaml
Where <release-name> is the name used to install the helm release originally (currently wms-prod) and <env> is the environment on which we are deploying (one of aws-dev, val, ope)```

ref. https://cgi-pathfinders.atlassian.net/browse/W9-46?atlOrigin=eyJpIjoiM2I0MGQzMmJiYjBhNDg1NzgxYmM1YjI0NzgyNTUwYWQiLCJwIjoiaiJ9
