### ISSUE TITLE
SuggestedFormat code incorrect

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/eumetsat-EOWS#365]
The GranuleDescriptor has code for using a `suggestedFormat` but the way is used is incorrect since it is not just a suggestion if the format is wrong for one of the granules there is not search for an alternative format (at least, I did not find it).

See [this](https://github.com/geotools/geotools/blob/a4f0d2a148534b7bf140e37328c3ae95d326b65d/modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/GranuleDescriptor.java#L383) code.

**Comment by simboss** [comment]
@dromagnoli why you closed this? I don't see any feedback or progres....

**Comment by dromagnoli** [comment]
@simboss 
I merged the related PR on geotools.

**Comment by dromagnoli** [comment]
I was doing a close and comment but for some reason the comment isn't there :|

**Comment by dromagnoli** [comment]
this one:
https://github.com/geotools/geotools/pull/3131

**Comment by simboss** [comment]
@dromagnoli if this has been done and backported to 2.17, we can close it.

Can you double check, thx?

**Comment by dromagnoli** [comment]
Yep. I have already backported it. closing it
