### ISSUE TITLE
Easier GeoServer reloads

### ISSUE THREAD

**Issue by randomorder** [geosolutions-it/eumetsat-EOWS#37]
It is currently tedious and time consuming to reload GeoServer slaves.

Current way to do it is a restart of GeoServer cluster service in Rancher which can take a few minutes.
Would be nice to have an easier / quicker way to do it

**Comment by simboss** [comment]
What is your suggestion here?

**Comment by Gnafu** [comment]
Fixed with a custom container in Rancher.
It will run on-demand, started from Rancher UI, signaling the GeoServer Slaves to reload.

No ssh tunnels or bash scripts required.
