### ISSUE TITLE
Harvesting a single file results into a directory scan anyway (due to implementation using FileFilters)

### ISSUE THREAD

**Issue by dromagnoli** [geosolutions-it/eumetsat-EOWS#374]
The current implementation of harvesting is based on a MosaicWalker setup on top of a FileFilter to refer that file.
This results anyway in a directory scan (even if using that filter) being performed by the ImageMosaicDirectoryWalker.
We should avoid that and providing directly the needed files to the walker so that no directory scan/directory filtering is performed at all.

**Comment by simboss** [comment]
@dromagnoli has this been done?

Can we close this then?

**Comment by dromagnoli** [comment]
Done
