### ISSUE TITLE
Country borders embedded in the OSM Layers in EUMETView NG

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/eumetsat-EOWS#377]
@simboss commented on [Fri Sep 11 2020](https://github.com/geosolutions-it/support/issues/855)

From [IMGMT-378](https://cgi-pathfinders.atlassian.net/browse/IMGMT-378).

This is high priority and simple. 
I already removed (as a test) two layers from the master config of the dark background, we need to do the same for the light one, deploy the change, clean the cache and then maybe a seed a little using master.

This is apparently a top priority for them.

**Comment by randomorder** [comment]
Done in DEV. Waiting for SSH access to OPE to deploy
![image](https://user-images.githubusercontent.com/5264230/93066065-cbddae00-f679-11ea-83a4-0982e9dbea55.png)
![image](https://user-images.githubusercontent.com/5264230/93066099-d8620680-f679-11ea-85b3-bb99e2b454a8.png)

**Comment by randomorder** [comment]
done on OPE as well. Waiting for feedback from Fabrizio Borgia

**Comment by randomorder** [comment]
issue closed in JIRA by Fabrizio
