### ISSUE TITLE
[AOB V] Raise GetCoverage limit to 1GB

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/eumetsat-EOWS#391]
From the client:

`The limit for the GetCoverage API response on EUMETView is 250 MB. EOWS should evaluate the implications of raising such limit to, say, 1 GB. If feasible and not harmful for the service, the limit should be raised.`

https://cgi-pathfinders.atlassian.net/browse/W9-18

**Comment by simboss** [comment]
Aside from doing this, which is a minor thing, we shall test it to see the effect on GeoServer.
I would test it especially with NetCDF data.

Let's discuss how to do this.

**Comment by randomorder** [comment]
I've applied the change for the download limit on the master instance in DEV: https://gitlab.cgi-dev.de/eows/wms/geoserver-data-dir/merge_requests/1

We want to test it before merging the MR

**Comment by randomorder** [comment]
@jemacchi 

Can you please test WCS version [1.0.0](https://view.cgi-dev.de/geoserver/ows?service=wcs&version=1.0.0&request=GetCapabilities) and [2.0.1](https://view.cgi-dev.de/geoserver/ows?service=WCS&version=2.0.1&request=GetCapabilities) and put it under pressure we want to understand if the limits we set are good enough.

Unfortunately this is not directly testable by the Eum client app so you'll have to use other client applications (maybe QGIS?)

**Comment by randomorder** [comment]
Moving to block. We have to wait for the deploy in VAL on Mon to move on with this to prevent this conf changed to be rolled out directly to VAL and OPE before testing

**Comment by jemacchi** [comment]
> Unfortunately this is not directly testable by the Eum client app so you'll have to use other client applications (maybe QGIS?)
@randomorder 
I tested layers (on dev) enabling Geoserver and the decoration.json file, using browser and simulating WMS calls (it works, but of course it's a manual test). I will try with QGIS.


> Moving to blocked

ok

**Comment by randomorder** [comment]
can you please resume this @jemacchi ?

**Comment by jemacchi** [comment]
@randomorder  I have checked/tested using QGIS calling WCS to geoserver-master (so can enable or disable layers and check logs)
It's working reasonably for layers I tested (ie. attached image show a set of layers). Just played with zoom, moving, etc (note: bandwidth, 20MB fiber for download)
 
![image](https://user-images.githubusercontent.com/1171099/107394107-4223f680-6ada-11eb-8d94-d50cc6017f51.png)

Checked logs in geoserver and everything looks as expected. 
Not sure how to check geoserver performance on responses (just for getting metrics instead of a sense of use)

**Comment by jemacchi** [comment]
@randomorder 
I have checked again after the pipeline execution you applied (in this case testing against slaves), and I can confirm you that value for maxOutputMemory has changed (attached image below) and that test using QGIS are working as expected (good response, no blocks or timeouts, with a reasonable time response).

![image](https://user-images.githubusercontent.com/1171099/107420404-a0ab9d80-6af7-11eb-966f-5d067d984c14.png)

Sample layers

![image](https://user-images.githubusercontent.com/1171099/107420430-a608e800-6af7-11eb-8b2f-33dde2fc25b5.png)

**Comment by randomorder** [comment]
ok thanks. You tested both version 1.0.0 and 2.0.1? What was the final size of the downloaded dataset?
Ideally we want to test something close to 1GB

**Comment by jemacchi** [comment]
@randomorder 
QGIS uses 1.0.0 on its native version. So, initial tests were done with 1.0.0 only. 
Fur purposes of 2.0.1 I have checked a QGIS plugin that it's supposed that should work for 2.0.1, but it failed when getCoverage service was call, so tried with browser/wget calls (and saving files, and playing with different subsets, etc)
In general, it worked as expected (no block or timeouts, and a reasonable time for download).

ie. (698 MB tiff file)
`wget -O test.tiff "https://view.cgi-dev.de/geoserver/wcs?SERVICE=WCS&COVERAGEID=copernicus__sentinel3a_olci_l1_rgb_fullres&VERSION=2.0.1&REQUEST=GetCoverage&FORMAT=image/tiff&subset=Lat(-54,39)&subset=Long(-60,0)"
`

![image](https://user-images.githubusercontent.com/1171099/107549440-9ac4c380-6bae-11eb-913a-dfd8e53994bf.png)

**Comment by randomorder** [comment]
landed in VAL
