### ISSUE TITLE
Prepare Docker Set up for the infrastructure

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/eumetsat-EOWS#4]
We have made two proposals for the test infrastructure based on Docker:

1. [Large Installation](https://docs.google.com/drawings/d/19pbeUFSKSz0jh_cnYSScA4JoM6RNL71geCCUjr3_f30/edit)  
2. [Small Installation](https://docs.google.com/drawings/d/1uWYoGo6j6VCSQuxn4nbIyQ4e8519ZUQgHlNNs2tTD8E/edit)

For the time being we are going to deploy the Small Installation and it is foreseen to use VMs coming from an Hetzner server made available by CGI (when? Hopefully soon).

**Comment by randomorder** [comment]
Confirm we are moving on with "Small Installation". installations step are tracked in the following Doc: https://goo.gl/yJ49Ts

**Comment by randomorder** [comment]
Rancher UI available at http://pf-rancher.eoss-cloud.it/
Currently having some issues with Rancher UI and proxy configuration, see #30 for status

**Comment by simboss** [comment]
Please, add a section in the wiki for this work.

**Comment by randomorder** [comment]
Wiki page created: https://github.com/geosolutions-it/eumetsat-EOWS/wiki/Development-Environment
