### ISSUE TITLE
Add all public layers to MapCache ConfigMap

### ISSUE THREAD

**Issue by randomorder** [geosolutions-it/eumetsat-EOWS#414]
Update the Mapcache ConfigMap with All PUBLICLY available layers

**Comment by lpasquali** [comment]
I easily (using jninja2 tamplating) generated from a template all the stanzas for 80 public layers not impacted by the restrictions in security data regular expressions

**Comment by randomorder** [comment]
please apply the new configmap with kubectl in DEV. Namespace "wms"

**Comment by randomorder** [comment]
and pushe the script [here](https://github.com/geosolutions-it/eumetsat-EOWS/) in a subdir called "WP9"

**Comment by lpasquali** [comment]
waiting for a fix on the image pull ongoing issue in the dev cluster

**Comment by lpasquali** [comment]
@randomorder 
https://gitlab.cgi-dev.de/eows/wms/helm-charts/merge_requests/6

**Comment by randomorder** [comment]
I've asked CGI to move on with the deploy

Have you pushed the script?

**Comment by randomorder** [comment]
CGI is testing in DEV

**Comment by randomorder** [comment]
this work has been deployed
