### ISSUE TITLE
Write a technical note on MapCache introduction

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/eumetsat-EOWS#416]
We should start from [this](https://docs.google.com/drawings/d/1bo-kbEE1qB_eKZQYtqas8dOXd7sMogQWrVGXJbm8UwE/edit) diagram and create a couple of pages technical proposal, similar to what we did for the overlay.

We need this by 7th of December.

**Comment by randomorder** [comment]
@simboss if you want to take a look: https://docs.google.com/document/d/1uztbqnTULI85SMhYUSiTgFyhJPH8kLxyNhVQ1R-wLxk/edit#
