### ISSUE TITLE
Prepare a technical documentfor the PostgreSQL Integration

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/eumetsat-EOWS#417]
We need to start with [this](https://docs.google.com/document/d/1BF3IqpgymfeTCjtsBkCyQ5C7WFVuFdO12FMiVJGiWCE/edit#heading=h.huwmetpb6w94) document and turn it into a technical note that we can share with the client.

We need this by December the 2nd.

**Comment by randomorder** [comment]
https://docs.google.com/document/d/1KOG3FEDRoYlQ7dJMSMhdvAd0cCR9CD243VSyNUugr54/edit
