### ISSUE TITLE
Deploy support on decorations and legends improvements

### ISSUE THREAD

**Issue by jemacchi** [geosolutions-it/eumetsat-EOWS#420]
- Deploy features related to the [Epic](https://github.com/geosolutions-it/eumetsat-EOWS/issues/359).
- Test developed features (mentioned in Epic) invoking calls to the WPS API.

**Comment by jemacchi** [comment]
@simboss  @randomorder 
Deployment was done in DEV environment (and improvement tested). Now CGI Frontend team will be working on changes in UI so they can integrate it. Rest to do deployments in VAL & OPE.
[https://cgi-pathfinders.atlassian.net/browse/W9-7](https://cgi-pathfinders.atlassian.net/browse/W9-7)

**Comment by simboss** [comment]
This is still pending for VAL from CGI, we shall ping him probably.

**Comment by jemacchi** [comment]
CGI team deployed in VAL and confirmed behavior. @simboss  should we move/close this ticket ?
