### ISSUE TITLE
Set up PostgreSQL cluster in DEV using Postgres Operator

### ISSUE THREAD

**Issue by randomorder** [geosolutions-it/eumetsat-EOWS#421]
Deploy a PG cluster in DEV environment using postgres operator

**Comment by lpasquali** [comment]
ui and operator deployed, now building the yaml for the actual cluster

**Comment by lpasquali** [comment]
cluster deployed

**Comment by lpasquali** [comment]
quick recap: we will hopefully resume this from today or tomorrow

**Comment by randomorder** [comment]
We have a window for DEV this Friday from 11:30 onwards. You can work on it in the afternoon @lpasquali, ok?

**Comment by lpasquali** [comment]
work on 14/12 was done, we tested the cluster (no pg_bouncer) and it worked fine, there was also some more data in the db this time so the tests had more "time frames" of data for a specific layer to test in the front-end apoplication

**Comment by randomorder** [comment]
@lpasquali please 
1 - re-enable the HA cluster in DEV
2 - test the pooling with PgBouncer

Perform point 1 today if possible

**Comment by lpasquali** [comment]
> @lpasquali please
> 1 - re-enable the HA cluster in DEV
> 2 - test the pooling with PgBouncer
> 
> Perform point 1 today if possible

atm the cluster should be up and running in DEV, I only changed back to the old postgres the datasources, should we leave DEV with new cluster for all holidays?

**Comment by randomorder** [comment]
yes please

**Comment by lpasquali** [comment]
@randomorder 
rollback procedure this includes restart of master:

```
kubectl exec -n wms -it wms-geoserver-master-set-0 bash
cd /var/geoserver/datadir/
cp jdbcstatusstore.props.backup jdbcstatusstore.props
cp jdbc-import-store.properties.backup  jdbc-import-store.properties
```

test master 
```
 kubectl rollout restart -n wms statefulset wms-geoserver-master-set 
```

then re-run the pipeline for the docer image on the slaves

**Comment by lpasquali** [comment]
@randomorder we are back on pg ha powered by zalando

**Comment by randomorder** [comment]
cool thx

looks like DEV is performing much better now

**Comment by randomorder** [comment]
Please remember to update environment variables in the Helm charts too @lpasquali . They're used by the [Importer](https://docs.geoserver.org/stable/en/user/extensions/importer/index.html) plugin to populate the histogram tables..

```
root@wms-geoserver-master-set-0:/var/geoserver/datadir/importer/scripts# cat update_histogram.sh
### NOTE: this script will need a postgresql client to be already installed
###
### For example : postgresql-client-9.6

##################################
# Set PSQL variables with defaults
##################################

export PGHOST=${PGHOST-localhost}
export PGPORT=${PGPORT-5432}
export PGDATABASE=${PGDATABASE-database}
export PGUSER=${PGUSER-username}
export PGPASSWORD=${PGPASSWORD-password}

##################################
# Actual query
##################################
TABLE_NAME=${2:-metopa}
# Remove namespace if the full name of the layer has been passed, instead of the table name
# This requires the layer name and the table name to be identical
TABLE_NAME=$(echo $TABLE_NAME | sed 's/^.*://')

psql -c "Insert into ${TABLE_NAME}_histogram  select time, st_setsrid(st_extent(the_geom)::geometry, 4326) as the_geom from ${TABLE_NAME} where time = '$1' group by time ON CONFLICT (time) DO UPDATE SET the_geom = EXCLUDED.the_geom"

```

**Comment by lpasquali** [comment]
> Please remember to update environment variables in the Helm charts too @lpasquali . They're used by the [Importer](https://docs.geoserver.org/stable/en/user/extensions/importer/index.html) plugin to populate the histogram tables..
> 
> ```
> root@wms-geoserver-master-set-0:/var/geoserver/datadir/importer/scripts# cat update_histogram.sh
> ### NOTE: this script will need a postgresql client to be already installed
> ###
> ### For example : postgresql-client-9.6
> 
> ##################################
> # Set PSQL variables with defaults
> ##################################
> 
> export PGHOST=${PGHOST-localhost}
> export PGPORT=${PGPORT-5432}
> export PGDATABASE=${PGDATABASE-database}
> export PGUSER=${PGUSER-username}
> export PGPASSWORD=${PGPASSWORD-password}
> 
> ##################################
> # Actual query
> ##################################
> TABLE_NAME=${2:-metopa}
> # Remove namespace if the full name of the layer has been passed, instead of the table name
> # This requires the layer name and the table name to be identical
> TABLE_NAME=$(echo $TABLE_NAME | sed 's/^.*://')
> 
> psql -c "Insert into ${TABLE_NAME}_histogram  select time, st_setsrid(st_extent(the_geom)::geometry, 4326) as the_geom from ${TABLE_NAME} where time = '$1' group by time ON CONFLICT (time) DO UPDATE SET the_geom = EXCLUDED.the_geom"
> ```

good to know, thanks, I will

**Comment by lpasquali** [comment]
@randomorder if rollout logic is clear to me, all we'd need to do, as database information is in default environment inside the chart for geoserver `charts/wms-geoserver/values.yaml`

all that should be needed is to add in the values file values-aws-dev.yaml for both slave and master statefulsets values:
```yaml
      pg:
        host: "geosolutions-wms-pg96-cluster"
```

I would not work in `charts/wms-geoserver/values.yaml` as it should be a file for defaults and changing stuff there will be applied on nany environment, also reading the file I see that password and username for the cluster is there too and it might be a good time to move it on each existing values file per environment (DEV/OPE/VAL).

**Comment by randomorder** [comment]
> @randomorder if rollout logic is clear to me, all we'd need to do, as database information is in default environment inside the chart for geoserver `charts/wms-geoserver/values.yaml`

makes sense
 
> all that should be needed is to add in the values file values-aws-dev.yaml for both slave and master statefulsets values:
> 
> ```yaml
>       pg:
>         host: "geosolutions-wms-pg96-cluster"
> ```
> 
> I would not work in `charts/wms-geoserver/values.yaml` as it should be a file for defaults and changing stuff there will be applied on nany environment, also reading the file I see that password and username for the cluster is there too and it might be a good time to move it on each existing values file per environment (DEV/OPE/VAL).

yes, please make a MR for that

**Comment by lpasquali** [comment]
In addidion to the proposed modification which would do the trick of overriding selectively the hostname for postgres indipendetly for each environment, there is still the need to ask CGI to make some modifications to the existing geoserver chart in orger to do an easy and painless switch betweeen the postgres:
1) context.xml we could ask to habdle different context.xml to be ingested in the context configmap [here](https://gitlab.cgi-dev.de/eows/wms/helm-charts/blob/master/charts/wms-geoserver/templates/configmap/configmap-context-file.yaml#L13) this could be done for example adding a global.eumetsatenv for each values file for DEV/OPE/VAL and then creating 3 `context.<env>.xml` files containing it accordigly.
2) the two files in datadir could become configmaps bind mounted in place: `/var/geoserver/datadir/jdbc-import-store.properties`, `/var/geoserver/datadir/jdbcstatusstore.props`
3) addition as above of to [here](https://gitlab.cgi-dev.de/eows/wms/helm-charts/blob/postgres_ha_implelemtation/values-aws-dev.yaml#L93-94) and [here](https://gitlab.cgi-dev.de/eows/wms/helm-charts/blob/postgres_ha_implelemtation/values-aws-dev.yaml#L120-121) in specified file :
```yaml
      pg:
        host: "geosolutions-wms-pg96-cluster"
```
point 3 is proposed in the same branch in which I added postgres charts, while point 1, 2 could be asked to be done by CGI

**Comment by randomorder** [comment]
Generally speaking, externalizing all references to postres is desirable. We'll ask CGI to help with it after we delivered Postgressql HA
