### ISSUE TITLE
Postgres Cluster Status Monitoring

### ISSUE THREAD

**Issue by randomorder** [geosolutions-it/eumetsat-EOWS#422]
```
·        how the cluster configuration can be monitored, that is the API endpoint to use to know which instance is serving the requests

·        basic procedures to recover from failures
```

**Comment by randomorder** [comment]
See my note in [the Tech note](https://mail-attachment.googleusercontent.com/attachment/u/0/?ui=2&ik=6972fa7574&attid=0.1&permmsgid=msg-a:r1856390993530343527&th=1760596e9adf9367&view=att&disp=inline&saddbat=ANGjdJ8pCfeiYJqThpN9PfYpGtECFucUam7EF5H5UnqILFb6h_I5GK8qQ4eIG0C9ZWKQLYIN1K25mx0S8S8lTtLqhrT7Goi6ztg221NksQhYZm5WE9ZZ91u1vaoYZULingUs42VTgFwXd7pVJHkJObJREBCcIni2iWQNHxt6mbvdqj1fW8FzyQzrgvTyFLTr5YHSudi_hHEb5O9x3tjuV-wCzMTE4LrajbRpzcHT32MqvVPpLs8Us8rkZhBqBJECWpb_S14BUb2pW9VzZ8PRwCSKrUPjgg1jOyJn82p-sULIcWrrdPoRnkhYlGpwp4UR-X0cX9AUsX3uOsTE0nhmcEVsh3h-K805Dx6p2fIX_od9b7NcAdzttEIGkyF6NlxJoDEmwGnQ9EH9pgM8k2IfdwU6-0_692vDHgbHtoXQOBLQO3iNabSjDHJNsCXQzvRYtzPeTqBIKx0XY5cUqRKTpFn-C3jjs5-s67AJO49-nJWQd0XQgIaR7-S2V-1Shj9zSW3nh47LZrzx66_HXWeznWZrV6ORYq7af8cqLssLwtjU1A7Cn9jS3fHksxXPOEz-LRWm4WhQl3-vC1IzEMYYQ3sSN8Q5ei7Y5QOMK_i1UMZ-AR0eYUyrndXZ4ZD6S6OZWN4a_6gs4Frhkts1GTsS_55FfvPPp95wLN0fdgl_oLZ37GgukfryjtZfLN6G-Rg) 
"Monitoring Considerations"

**Comment by randomorder** [comment]
we can close this one, right @lpasquali ?

**Comment by lpasquali** [comment]
> we can close this one, right @lpasquali ?

As we agreed I documented all the possible GET requests to the operator API to check for status information, this part should be satisfied, but it could be useful to integrate something as we deploy the prometheus-operator-ui so the answer is yes, but we'll probably re-touch the document about that.
