### ISSUE TITLE
Estimate resource requirements for Postgres Cluster instances

### ISSUE THREAD

**Issue by randomorder** [geosolutions-it/eumetsat-EOWS#423]

**Comment by lpasquali** [comment]
I did some kubectl top on namespaces of DEV, OPE, VAL (dev has new cluster right now):
```
VAL - wms-geoserver-postgres-wms-geoserver-set-0                 1m           68Mi            
OPE - wms-geoserver-postgres-wms-geoserver-set-0                 161m         4181Mi          
DEV - geosolutions-wms-pg96-cluster-0                            3m           371Mi           
DEV - geosolutions-wms-pg96-cluster-1                            3m           209Mi    
```
Calculations are based on the OPE cluster, the one with most occupied resources.
I would give these resources to each pod of the new cluster:
```
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: "1"
      memory: "8Gi"
```
These values should be very safe for any environment, including DEV where there are less resources, but if in dev they are considered overall too much, we could put 2Gi for dev.
I do not think there will be the need to raise them any time soon, they should last long as is for EUMETSAT, but giving guidelines for alerts in prometheus/alertmanager it would be easy to raise, or eventually even lower these values. Concerning requests it's ok to keep them low, pods will request up their limits.

**Comment by randomorder** [comment]
> I did some kubectl top on namespaces of DEV, OPE, VAL (dev has new cluster right now):
> 
> ```
> VAL - wms-geoserver-postgres-wms-geoserver-set-0                 1m           68Mi            
> OPE - wms-geoserver-postgres-wms-geoserver-set-0                 161m         4181Mi          
> DEV - geosolutions-wms-pg96-cluster-0                            3m           371Mi           
> DEV - geosolutions-wms-pg96-cluster-1                            3m           209Mi    
> ```
> 
> Calculations are based on the OPE cluster, the one with most occupied resources.
> I would give these resources to each pod of the new cluster:

So, you're estimating resources on the current usage on OPE? That's not a good way to estimate these values (we don't even know if it is under pressure at the moment or not)

> ```
>   resources:
>     requests:
>       cpu: 100m
>       memory: 100Mi

Is that 0.1 CPU cores and 100MB of RAM?

>     limits:
>       cpu: "1"
>       memory: "8Gi"
> ```
> 
> These values should be very safe for any environment, including DEV where there are less resources, but if in dev they are considered overall too much, we could put 2Gi for dev.

We should be able to set different values for different environments using heml charts

> I do not think there will be the need to raise them any time soon, they should last long as is for EUMETSAT, but giving guidelines for alerts in prometheus/alertmanager it would be easy to raise, or eventually even lower these values. Concerning requests it's ok to keep them low, pods will request up their limits.

we don't have access to prometheus. I am not sure what visibility they have on that either

**Comment by lpasquali** [comment]
```
  resources:
    requests:
      cpu: "1"
      memory: "8Gi"
    limits:
      cpu: "2"
      memory: "16Gi"
```

antiaffinity is handled, I also will allocate all the shared buffers and caching for a 8Gb instance using these postgres configuration values:
```
# DB Version: 9.6
# OS Type: linux
# DB Type: mixed
# Total Memory (RAM): 8 GB
# CPUs num: 2
# Connections num: 500
# Data Storage: san

max_connections = 500
shared_buffers = 2GB
effective_cache_size = 6GB
maintenance_work_mem = 512MB
checkpoint_completion_target = 0.9
wal_buffers = 16MB
default_statistics_target = 100
random_page_cost = 1.1
effective_io_concurrency = 300
work_mem = 2097kB
min_wal_size = 1GB
max_wal_size = 4GB
max_worker_processes = 2
max_parallel_workers_per_gather = 1
```

**Comment by randomorder** [comment]
please update these values as agreed @lpasquali

**Comment by lpasquali** [comment]
```
  resources:
    requests:
      cpu: "4"
      memory: "4Gi"
    limits:
      cpu: "4"
      memory: "8Gi"
```
