### ISSUE TITLE
Installation instructions for Postgres cluster and Postgres Operator

### ISSUE THREAD

**Issue by randomorder** [geosolutions-it/eumetsat-EOWS#424]

**Comment by lpasquali** [comment]
@randomorder just to be sure: this will be an internal document iirc

**Comment by randomorder** [comment]
no, this is for Eumetsat / CGI

**Comment by lpasquali** [comment]
https://docs.google.com/document/d/10A1BWfP44vTCu9TDZc0W-iI9AzZqE81p9d2ySxG4g1Q/edit#heading=h.mfto6dfqfqk4

**Comment by randomorder** [comment]
minor changes, please check my comments

**Comment by lpasquali** [comment]
@randomorder changes done, let me know if it is now ok

**Comment by randomorder** [comment]
thanks
