### ISSUE TITLE
Migrate Data to new Postgres cluster

### ISSUE THREAD

**Issue by randomorder** [geosolutions-it/eumetsat-EOWS#425]

**Comment by lpasquali** [comment]
data imported

**Comment by lpasquali** [comment]
@randomorder ready to do the needed modifications to geoserver

**Comment by lpasquali** [comment]
waiting for OK to work on DEV

**Comment by randomorder** [comment]
Waiting for the cluster to be set up in VAL and OPE to move on with this

**Comment by lpasquali** [comment]
we imported data in VAL
