### ISSUE TITLE
sentinel3a_wst_orbitfootprint - Copernicus S3A Orbital Tracks

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/eumetsat-EOWS#430]
Sampe data [here](https://www.dropbox.com/sh/6e63zlj0jpj6qjq/AAAkkAIsP5un0uw240qLg2Uha?dl=0).
**OGRINFO**

> INFO: Open of `Sentinel3A_WST_OrbitFootprint_PlateCarree_20201130000831_20201130014731.shp'
      using driver `ESRI Shapefile' successful.
Layer name: Sentinel3A_WST_OrbitFootprint_PlateCarree_20201130000831_20201130014731
Metadata:
  DBF_DATE_LAST_UPDATE=2020-11-30
Geometry: Polygon
Feature Count: 35
Extent: (-180.000000, -85.918022) - (180.000000, 90.000000)
Layer SRS WKT:
GEOGCRS["WGS 84",
    DATUM["D_unknown",
        ELLIPSOID["WGS84",6378137,298.257223563,
            LENGTHUNIT["metre",1,
                ID["EPSG",9001]]]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["Degree",0.0174532925199433]],
    CS[ellipsoidal,2],
        AXIS["longitude",east,
            ORDER[1],
            ANGLEUNIT["Degree",0.0174532925199433]],
        AXIS["latitude",north,
            ORDER[2],
            ANGLEUNIT["Degree",0.0174532925199433]]]
Data axis to CRS axis mapping: 1,2
time: String (254.0)

**Comment by jemacchi** [comment]
@simboss 
We were checking ticket with @randomorder . 
Need to confirm, for these layers, is  workspace = Copernicous right ?

**Comment by jemacchi** [comment]
@randomorder @simboss 
Final documentation updated [here](https://docs.google.com/document/d/1lOEm102msE6-zec_o21Uy7iVfdqO4ryaLn1c1b_S6Dc/edit#heading=h.57kv8ekdz6j3)

Test case/sample was implemented on Dev enviroment (only for Metop1 dataset)
