### ISSUE TITLE
Implement an asynch rendering service

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/eumetsat-EOWS#44]
From user stories:
- As a user I shall choose or not to add a footer to the downloaded image containing the timestamp and the EUMETSAT logo
- As a user I want to be able to download recurrently and automatically data or visualisations with a batch client
- As a user I want to download the animations
- As a user I want to download in different formats as an image what I am currently visualizing or the full extent of the image

Apparently, support for external layers is not needed anymore, however I would keep into account. It is the client that drives the process and initiate the exchange.

**Comment by aaime** [comment]
This is all done, moving to complete
