### ISSUE TITLE
Some of the publicly available layer(Group)s are not cached in MapCache

### ISSUE THREAD

**Issue by randomorder** [geosolutions-it/eumetsat-EOWS#440]
All publicly available layers should have been configured in MapCache.

MC [here](https://gitlab.cgi-dev.de/eows/wms/helm-charts/blob/master/charts/wms-geoserver/configFiles/mapcache.xml)

For instance, these are missing:
- copernicus:daily_sentinel3ab_olci_l1_rgb_fulres
- copernicus:daily_sentinel3ab_olci_l2_chl_fullres
- copernicus:daily_sentinel3ab_slstr_l2p_sst_fullres
- osmgray:dark
- osmgray:dark_bg
- osmgray:dark_labels
- osmgray:light
- osmgray:light_bg
- osmgray:light_labels

Check all layers and layer(group)s, not just the ones listed above

**Comment by lpasquali** [comment]
@randomorder in the meanwhile I added the one listed now checking all for missing

**Comment by lpasquali** [comment]
list of only added tilesets:
``` 
 <tileset name="osmgray:dark">
  <tileset name="osmgray:dark_bg">
  <tileset name="osmgray:dark_labels">
  <tileset name="osmgray:light">
  <tileset name="osmgray:light_bg">
  <tileset name="osmgray:light_labels">
  <tileset name="copernicus:daily_sentinel3ab_olci_l1_rgb_fulres">
  <tileset name="copernicus:daily_sentinel3ab_olci_l2_chl_fullres">
  <tileset name="copernicus:daily_sentinel3ab_slstr_l2p_sst_fullres">
  <tileset name="mumi:wideareacoverage_rgbnatcolour">
  <tileset name="mumi:worldcloudmap_ir108">
  <tileset name="test:l3">
```

**Comment by lpasquali** [comment]
back from done to make a script for this

**Comment by lpasquali** [comment]
I should have done also the scripts to facilitate anyone but me to do it, the scriopts directory has a short doc on how to use its content @randomorder

**Comment by lpasquali** [comment]
https://gitlab.cgi-dev.de/eows/wms/helm-charts/tree/mapcache_tileset_fix/charts/wms-geoserver/scripts

**Comment by lpasquali** [comment]
@randomorder this has been superseded by #444 going to close this
