### ISSUE TITLE
Lower Metatiling Factor in MapCache configuration

### ISSUE THREAD

**Issue by randomorder** [geosolutions-it/eumetsat-EOWS#444]
https://gitlab.cgi-dev.de/eows/wms/helm-charts/blob/master/charts/wms-geoserver/configFiles/mapcache.xml

Currently set to 4x4 for all layers. With 512x512 tiles that turns into a 2048x2048 request to the backend which can be a bit heavy

Let's lower it to 1x1 for all layers withouth labels and copy the value from geowebcache for layers with labels

Keep things as they are for background layers with lables and coming from the geopackages

**Comment by randomorder** [comment]
# Backgrounds and Overlays
osmgray:osm_places
osmgray:waterareas
osmgray:waterways
osmgray:builtup_area
osmgray:land_polygons
osmgray:ne_10m_admin_0_boundary_lines_land
osmgray:ne_10m_admin_0_countries_points
osmgray:ne_10m_admin_1_states_provinces_lines
osmgray:ne_10m_bathymetry
osmgray:osm_places
osmgray:simplified_land_polygons
osmgray:waterareas
osmgray:waterways
osmgray:light_bg
osmgray:dark_bg
osmgray:light
osmgray:light_labels
osmgray:dark
osmgray:dark_labels
backgrounds:ne_10m_coastline
backgrounds:ne_background
backgrounds:ne_boundary_lines_land
backgrounds:ne_gray

**Comment by randomorder** [comment]
https://gitlab.cgi-dev.de/eows/wms/helm-charts/merge_requests/8/diffs?commit_id=a3557b7747cf4f3f004c132aa321b51ef866f16c

**Comment by randomorder** [comment]
https://gitlab.cgi-dev.de/eows/wms/helm-charts/blob/9f56976e3da4e9a9a10a26b2e5a9b1054811b420/charts/wms-geoserver/configFiles/mapcache.xml

**Comment by randomorder** [comment]
We may want to update to the scripts @lpasquali It's becoming more complex

Basically we want custom metatile, expire and auto_expire for the layers

Maybe adding  info to the input file along with the layer(group)s names in a CSV?
something along these lines:
```
#layer name, metatile, expires, auto_expire
copernicus:daily_sentinel3ab_olci_l1_rgb_fulres, 1, 604800, 2592000
osmgray:builtup_area, 3, 604800, 0
```

Where -1 applies only for expires or auto_expire and means don't add the tag to the tileset (which in turn for MapCache means expires to 300 secs and auto_expire is+ infinity)

How long would it take to implement?

**Comment by simboss** [comment]
@randomorder we also need to make sure that from mapcache we strip the tiled=true parameter on public layers to not activate GWC in case we set the metatling factor to 1.

*This is super important*.

**Comment by randomorder** [comment]
There's a problem with the new config @lpasquali 

`tileset "copernicus:daily_sentinel3ab_olci_l2_chl_fullres" references source "copernicus:daily_sentinel3ab_olci_l2_chl_fullres", but it is not configured`

At a first glance, the problem seems to be here:
https://gitlab.cgi-dev.de/eows/wms/helm-charts/blob/9f56976e3da4e9a9a10a26b2e5a9b1054811b420/charts/wms-geoserver/configFiles/mapcache.xml#L2479-2512

**Comment by lpasquali** [comment]
I tested on dev, on monday I will make the mr as first thing

**Comment by simboss** [comment]
@allyoucanmap make sure we cover all the public layers!

**Comment by randomorder** [comment]
@lpasquali I had a chat w/ Simone

Let's do this

## Metatiling 2x2:
osmgray:light_bg
osmgray:dark_bg
osmgray:light
osmgray:light_labels
osmgray:dark
osmgray:dark_labels

Everything else set to 1x1

k?

**Comment by simboss** [comment]
@randomorder @lpasquali as per my chat with @randomorder let's not expose the underlying OSM layers!

**Comment by randomorder** [comment]
we'll tackle that ins #453

**Comment by lpasquali** [comment]
> @lpasquali I had a chat w/ Simone
> 
> Let's do this
> 
> ## Metatiling 2x2:
> osmgray:light_bg
> osmgray:dark_bg
> osmgray:light
> osmgray:light_labels
> osmgray:dark
> osmgray:dark_labels
> 
> Everything else set to 1x1
> 
> k?

as of now there are still 3x3 in the config I worked on last Friday, should it be left or should I make them one of the two above? if second case, which one?

@randomorder

**Comment by randomorder** [comment]
Please check my comment above

> Let's do this
> 
> ## Metatiling 2x2:
> osmgray:light_bg
> osmgray:dark_bg
> osmgray:light
> osmgray:light_labels
> osmgray:dark
> osmgray:dark_labels
> 
> Everything else set to 1x1

**Comment by lpasquali** [comment]
@randomorder I prepared a new mapcache.xml with the requested metatiling

**Comment by lpasquali** [comment]
@randomorder re-used same branch last used, I re-checked layers carefully, made MR for new mapcache.xml 

https://gitlab.cgi-dev.de/eows/wms/helm-charts/merge_requests/12

**Comment by randomorder** [comment]
@lpasquali 
CGI merged MC config again and it's broken again

https://cgi-pathfinders.atlassian.net/browse/W9-21?focusedCommentId=14048

https://gitlab.cgi-dev.de/eows/wms/helm-charts/blob/2b1d9408eb7dd302856a13be5d15c4b51dc8780f/charts/wms-geoserver/configFiles/mapcache.xml#L2590

I tough you tested it?

**Comment by lpasquali** [comment]
> I tough you tested it?
yes I did, but I probably did some mistake while transoforming it to mapcache.xml from a configmap.
I found a way to "lint" mapcache.xml though, by compiling it locally (quite easy, no need to install it cfr https://mapserver.org/mapcache/install.html) then obtain mapcache_detail, I can reproduce the error:
```
```

**Comment by lpasquali** [comment]
@randomorder I fixed the mapacahe.xml and checked that it is a working configuration file for mapcache as exposed above

**Comment by randomorder** [comment]
deployed in DEV

**Comment by randomorder** [comment]
deployed in VAL
