### ISSUE TITLE
Configure ControlFlow

### ISSUE THREAD

**Issue by randomorder** [geosolutions-it/eumetsat-EOWS#446]
https://gitlab.cgi-dev.de/eows/wms/geoserver-data-dir/blob/master/controlflow.properties

controlflow.properties is empty

https://github.com/geosolutions-it/eumetsat-EOWS/issues/441

**Comment by randomorder** [comment]
Trying to assess the amount of HW resources we have available for GS:

In OPE we have 9 worker nodes, each one with 16 Cores and 32 GB RAM. Each node has 20-30 containers running

GeoServer containers are distributed evenly on the nodes by default scheduler policy, I don't see this being enforced at any level and it should be. We should try to avoid deploying on the same nodes as PostgreSQL containers as well with taints and tolerations.

There is an explicit request (not a limit, a request) [for 2 CPU Cores per GeoServer](https://gitlab.cgi-dev.de/eows/wms/helm-charts/blob/master/charts/wms-geoserver/templates/statefulsets/statefulset-slave.yaml#L92)  . I would increase it to 4. I can get in touch with CGI and EUM and ask if it can be increased @simboss 

For the moment let's assume that each GS has 2 dedicated cores available tough it probably can spike up quite higher than that.

**Comment by randomorder** [comment]
### Reasoning

- there are 6 GS slaves instances in OPE
- there is no domain sharding as of now
- WMS direct integration is enabled
- there is MapCache in the mix so "in theory" when a request hits GeoServer is likely going to be a MISS (for public layers)
- we don't want to be too conservative and start getting 500 errors in the client. It's hard to test and painful to get these changes from DEV to OPE

### Proposed config 

```
timeout=20
ows.global=100

user=8
ows.gwc=100
ows.wms.getmap=16
ows.wps.execute=8
ows.wmts.describedomains=32
ows.wmts.gethistogram=32

user.ows.wms=20/s;1s
user.ows.wmts=16/m;1s
user.ows.wps=6/m;10s
```

**Comment by randomorder** [comment]
applied in DEV

**Comment by randomorder** [comment]
deployed in VAL

**Comment by simboss** [comment]
@randomorder can we document this ?

**Comment by randomorder** [comment]
versioned [here](https://gitlab.cgi-dev.de/eows/wms/geoserver/data-dir/blob/master/controlflow.properties)
