### ISSUE TITLE
Review caching settings for MapCache

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/eumetsat-EOWS#448]
- tiles on disk should not expire (for background layers and overlays) or expire after 1 month (for all other layers)
- http caching headers should be 1 week for all layers

**Comment by randomorder** [comment]
https://gitlab.cgi-dev.de/eows/wms/helm-charts/merge_requests/8/diffs?commit_id=a3557b7747cf4f3f004c132aa321b51ef866f16c

**Comment by randomorder** [comment]
something odd going on with the automations @simboss 
![image](https://user-images.githubusercontent.com/5264230/102075558-b443cc00-3e06-11eb-9185-46a33d8c85b6.png)
several issues are moved back to backlog

**Comment by randomorder** [comment]
MR submitted
