### ISSUE TITLE
Installation and Operations Manual

### ISSUE THREAD

**Issue by randomorder** [geosolutions-it/eumetsat-EOWS#452]
To capture info on how to install and operate the PG cluster in  K8s.

Remember it must describe how to update the cluster definition and postgresql configuration.

Special requests by CGI:
·        how the cluster configuration can be monitored, that is the API endpoint to use to know which instance is serving the requests
·        basic procedures to recover from failures

**Comment by lpasquali** [comment]
@randomorder this document will be used by the client

**Comment by randomorder** [comment]
done @lpasquali ?

**Comment by lpasquali** [comment]
this is the document @randomorder https://docs.google.com/document/d/1xkuFshYSHsSEg2CIu5gNHGA9SUK4kyZSgUWq-fVnVG8/edit#

**Comment by randomorder** [comment]
Please also add explicit  explanations on:
- how to check the logs
- how to restart the instances (or the cluster)
- how to make configutation changes to postgresql (equivalent to chaning postgresql.conf)

**Comment by lpasquali** [comment]
I should have implemented all the requested additions @randomorder

**Comment by randomorder** [comment]
thanks
