### ISSUE TITLE
Review GetCapabilities and Hide unused layers

### ISSUE THREAD

**Issue by randomorder** [geosolutions-it/eumetsat-EOWS#453]
Hide all layers that are not being used by the client application. Especially those that part of the OSM layergroups.

For layergroups, we can set the mode to [Opaque](https://docs.geoserver.org/latest/en/user/data/webadmin/layergroups.html#layer-group-modes)  and test it in DEV

**Comment by simboss** [comment]
@randomorder we should try to slip this in with the next batch of changes.
It's small but useful.

**Comment by randomorder** [comment]
Landed in VAL
