### ISSUE TITLE
Document EUM decorator configuration

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/eumetsat-EOWS#455]
We shall prepare a small document about how to manage the decorators we prepared for EUM starting form the technical document we sent them.

This shall be a few pages not more.

**Comment by jemacchi** [comment]
@simboss please check if [this document](https://docs.google.com/document/d/1p3BG3JR3b4zUF6O6m16Cgvb1VWhfD1lVRJhCyxzwd10/edit?usp=sharing) is clear.

It's focused on how to add layouts in the context of Eumetsat (assuming that reader understand what a decoration file implies. BTW, I just added also some references, so if required, any reader can go to Geoserver documentation)

**Comment by jemacchi** [comment]
@simboss  I have added a new section in [documentation](https://docs.google.com/document/d/1p3BG3JR3b4zUF6O6m16Cgvb1VWhfD1lVRJhCyxzwd10/) related to Freemaker mechanism and how that is working on text decorations for Geoserver. Please check and let me know if it's clear (and in case we need to extend for more detail)

**Comment by randomorder** [comment]
can we close this one @simboss ?
