### ISSUE TITLE
Grey background in Legends

### ISSUE THREAD

**Issue by randomorder** [geosolutions-it/eumetsat-EOWS#458]
It is noticeable in DEV. There's a grey background in the legents (default TOC precipitation layer in the example)

![Eumetsat_view_2020-04-01T0730 (2).png](https://images.zenhubusercontent.com/5cd59eb418690954352b7621/e70d9866-12b5-41ee-a51c-8ddbb1553927)

**Comment by randomorder** [comment]
Is this a regression? Can you please look at it @jemacchi ?

**Comment by jemacchi** [comment]
@randomorder 
Found the issue. 
In files left.xml and right.xml I have commented the line that enables bgcolor as part of the styling.
Now fixed in development environment (modified them into GS master datadir, and triggered a build&deploy so GS slaves copy the same datadir)

**Comment by simboss** [comment]
@jemacchi the legends should fade seamlessly with the top bar.

Make sure the config is like that.

**Comment by simboss** [comment]
I still see the difference.

**Comment by jemacchi** [comment]
I'm testing using postman (since I ensure that way that I'm hitting directly to the geoservers). And getting this result:

![response](https://user-images.githubusercontent.com/1171099/102932008-42aaf400-447e-11eb-8302-8d43158ea134.png)

I'm checking now with the EUMETSAT client.

**Comment by jemacchi** [comment]
@simboss 
tried with a simple request using EUMETSAT client, 10 mins ago and got this response
![Unsaved_session_2020-02-17T0745 (2)](https://user-images.githubusercontent.com/1171099/102933304-ccf45780-4480-11eb-8eb0-6b093617db8e.png)

Now I'm trying to access again, and continue testing other cases, but the client is not usable, pods in kubernetes were removed, and cannot access https://gitlab.cgi-dev.de/eows/wms/  (is CGI now shutting down instances daily?)

**Comment by simboss** [comment]
Everything is shut down at night and during weekends.
Right @randomorder ?

**Comment by randomorder** [comment]
yes
the cluster was restarted at 07:00 Italy time

**Comment by jemacchi** [comment]
@simboss @randomorder 
ok. I understood that it was only on weekends, but good to know that is daily too.

Regarding issue, please check yourself too. I have tested:
1) Postman, working.

![response](https://user-images.githubusercontent.com/1171099/102998835-b85aa280-4506-11eb-8d0e-85456618712b.png)

2) Using Eumetsat client (see images below),  working.

Selection:
![Captura de pantalla de 2020-12-23 09-56-09](https://user-images.githubusercontent.com/1171099/102998152-5e0d1200-4505-11eb-9ba6-ffebb9b6e9fb.png)

Result:
![Eumetsat_view_2020-02-17T0745 (2)](https://user-images.githubusercontent.com/1171099/102998846-c0b2dd80-4506-11eb-8706-603143f4b319.png)

**Comment by simboss** [comment]
I just checked this in Validation with the default layers (Precipitation and Airmas) 

![Clipboard01](https://user-images.githubusercontent.com/693880/104314374-9fc42380-54d9-11eb-90ed-d43e6ed61cd1.jpg)

and here below the result I am getting, which is not correct (the gray top bar is not covering the whole area!). Feedback @jemacchi ?
![Eumetsat_view_2021-01-12T1145](https://user-images.githubusercontent.com/693880/104314279-7c00dd80-54d9-11eb-9a82-7db8c3770e43.png)

**Comment by jemacchi** [comment]
@simboss space on topbar/header it's there since in the decorator xml associated file, the size is 1855. 

![image](https://user-images.githubusercontent.com/1171099/104323668-3508ed00-54c5-11eb-944c-03e3e10cd91a.png)

It will continuosly happen as much as width of requested download is bigger than the value defined in the header. Similarly to what it's happening with the bottom_bar, an approach would be to define the size of the header image with a value = 10000 (note: if someone ask for +10000 pixels width it will fail then)

**Comment by simboss** [comment]
@jemacchi please, liase with @randomorder and put this to 10000 as well.
Please, update the legend decorator document with these tricks before we send it to EUM.

**Comment by jemacchi** [comment]
@simboss  @randomorder 
[Document updated](https://docs.google.com/document/d/1p3BG3JR3b4zUF6O6m16Cgvb1VWhfD1lVRJhCyxzwd10/edit#) now using same approach as per bottom_bar image.

Updated in Dev env settings.

**Comment by randomorder** [comment]
@jemacchi can you tell me exactly what files have changed and how?
I want to report to CGI

**Comment by jemacchi** [comment]
> @jemacchi can you tell me exactly what files have changed and how?
> I want to report to CGI

@randomorder 

Deleted:  
 - bg-FBFBFB.png 

Created:   
 - bg_fbfbfb_10kx120.png

Modified: 
- footer25.xml
- footer30.xml
- footer60.xml
