### ISSUE TITLE
Issue with GeoTiff and No Data #2

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/eumetsat-EOWS#461]
**Original GeoTiff** [here](https://www.dropbox.com/s/2uua94pf2vq44vq/WideAreaCoverage_RGBAirmass_PlateCarree_2011010000.tif?dl=0).
**Optimized GeoTiff** [here](https://www.dropbox.com/s/21caa939t0xpugg/WideAreaCoverage_RGBAirmass_PlateCarree_2011010000_opt.tif?dl=0).
Optimizations steps as follows:

- gdal_translate -co "TILED=YES" -co "BLOCKXSIZE=512" -co "BLOCKYSIZE=512" -mo "NO_DATA_VALUES=0 0 0 " -co "COMPRESS=DEFLATE"  -a_nodata 0 WideAreaCoverage_RGBAirmass_PlateCarree_2011010000.tif WideAreaCoverage_RGBAirmass_PlateCarree_2011010000_opt.tif
- gdaladdo -r bilinear --config COMPRESS_OVERVIEW DEFLATE --config GDAL_TIFF_OVR_BLOCKSIZE 512 WideAreaCoverage_RGBAirmass_PlateCarree_2011010000_opt.tif

Issue
Strange artifacts (see video attached) appear at different resolution levels, which looks NODATA management issues.
Disabling map wrapping does not help.
Notice that we forced in the metadata (0,0,0) as nodata triplet so what is happening here is strange.

It looks some pixels where one of the band has value 0 turns the entire pixel to zero for certain overviews!
![eum-issue2](https://user-images.githubusercontent.com/693880/104893520-d2f03200-5973-11eb-8d4c-835d65b12c36.gif)

**Comment by dromagnoli** [comment]
Argh!
the metadata flag is wrong :)

-mo "NO_DATA_VALUES=0 0 0 "

It should be:

-mo "NODATA_VALUES=0 0 0 "

with just one underscore between NODATA and VALUES :)

Once fixed, it worked on my test

**Comment by simboss** [comment]
@dromagnoli what about the -a no_data shall I do anything with it?

I mean, do I need to add it or can I simply ignore it since we have no data in the original files?

**Comment by dromagnoli** [comment]
I would remove that piece since it's already there
