### ISSUE TITLE
Actual Implementation for improving animation memory usage

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/eumetsat-EOWS#468]
Reminder, we need to backport on their custom branch as per the wiki.

**Comment by aaime** [comment]
Here it is: https://github.com/geoserver/geoserver/pull/4879

It only covers not going OOM, now the two threads can have at most one image in queue, meaning at any point in time there can be 3 images, one being encoded, one in queue, and one produced that the map renderer is trying to put in the queue.
Used some Eumetsat animation, made it generate a large image per frame, with 124 frames, and it did not go OOM...

I did ntot work on a new memory limit though. Now we have:
* The WMS GetMap limits, verified they are being honored
* The maximum number of frames in an animation

Those two are already effectively putting a cap on the max output size, wmsLimit * numberOfFrames.
Not sure we need another, but open to suggestions.

In the main thread, we also discussed using the rasterWriteLimit already applied for rasters, or creating a new one for animations that works the same way, "with * height * bpp * frames" (so uncompressed size cap, we cannot predict how much they will compress).

**Comment by simboss** [comment]
@aaime can you think about a GUI for the download process. Please, provide doc as well also for older version.

As a side job I would also remove the WMS animator and update the doc.

**Comment by aaime** [comment]
The GUI has been backported to the EOWS branch. I still have to remove the WMS animator

**Comment by simboss** [comment]
@aaime open a separate issue for that
