### ISSUE TITLE
Test VDI Access

### ISSUE THREAD

**Issue by randomorder** [geosolutions-it/eumetsat-EOWS#472]
make sure you have access to the VDI and the instructions in the GDocs are clear

**Comment by lpasquali** [comment]
FYI @randomorder a few months ago I had my phone replaced by apple care, I asked for new RSA token

**Comment by lpasquali** [comment]
waiting for new rsa token

**Comment by lpasquali** [comment]
rsa token done, but it looks like I have no more a vdi assigned, because vmware horizon works with given credentials but I get error that I'm not entitled for any VDI

**Comment by lpasquali** [comment]
> rsa token done, but it looks like I have no more a vdi assigned, because vmware horizon works with given credentials but I get error that I'm not entitled for any VDI

11 days ago I mailed eumetsat about the subsequent problem I had above after my rsa token was successfully restored, still no answer @randomorder going to ping them today

**Comment by randomorder** [comment]
Please do, this is quite important and put me in CC

VAL and OPE are being migrated to the new infrastructure and you'll Need the VDI to be able to access them and there are planned activities to carry on on those machines in the next week or two

**Comment by randomorder** [comment]
please ping them immediately @lpasquali

**Comment by lpasquali** [comment]
> please ping them immediately @lpasquali

done @randomorder I sent them evidence of the issue

**Comment by lpasquali** [comment]
@randomorder I just need to figure out ho to log in into the new "offline vdi" that is a linux box, the regular vdi with windows 10 works. I asked for more information to EUMETSAT

**Comment by lpasquali** [comment]
> @randomorder I just need to figure out how to log in into the new "offline vdi" that is a linux box, the regular vdi with windows 10 works. I asked for more information to EUMETSAT

I'm all ok with both VDIs @randomorder I think you can close
