### ISSUE TITLE
Improve GeoServer deployment

### ISSUE THREAD

**Issue by randomorder** [geosolutions-it/eumetsat-EOWS#52]
- [x] Setup Analytics on the backend services
- [x] Single Docker image instead of two (one for master and one for slave)
- [x] Setup Monitoring / Alerting services
- [ ] Evaluate the possibility to setup a Jenkins instance in the infrastructure to manage deployment (currently on GeoSolutions infrastructure using Jenkins 1.6). Jenkins 2 would allow for a better use of Pipelines and version Jenkins pipelines code as well

**Comment by simboss** [comment]
I am splitting this in two user stories.

**Comment by simboss** [comment]
Let's discuss about Jenkins, but we might want to leave this for sprint 3.

**Comment by randomorder** [comment]
As of now Jenkins is not required. Closing for the moment
