### ISSUE TITLE
Scale  GeoServer on the Development infrastructure

### ISSUE THREAD

**Issue by randomorder** [geosolutions-it/eumetsat-EOWS#53]
- [x] Currently all containers run on a single host. Would be nice to setup more hosts and test scaling with Rancher
- [ ] Would be nice to have mechanisms in place to scale GeoServer cluster automatically based on some criterias (for instance load,  #requests/second, ...)

**Comment by simboss** [comment]
I will split this in two.

**Comment by randomorder** [comment]
Infrastructure setup is taken care by CGI. Reportedly will be able to scale the services but won't be automatic, at least not in the initial implementation in OTC
