### ISSUE TITLE
Scale Postgres on the Development infrastructure 

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/eumetsat-EOWS#56]
- [ ] Currently we have a single container for PostGIS. Would be nice to scale it to a cluster
- [ ] Would be nice to have mechanisms in place to easilly scale PostGIS cluster

**Comment by randomorder** [comment]
This have to be implemented using Kubernetes features before users ramp up

**Comment by randomorder** [comment]
This have to be implemented using Kubernetes features before users ramp up
