### ISSUE TITLE
Prepare Docker Image for GeoServer

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/eumetsat-EOWS#6]

**Comment by randomorder** [comment]
Docker Image should:

[ ] Use Apache Tomcat as Application Server instead of embedded Jetty
[ ] Be based on official Apache Tomcat Docker image
[ ] Allow for easy customization of the following:
    - GeoServer's Installed plugins
    - GeoServer's configuration directory path
    - GeoServer's  logs directory path
    - GeoServer's  GeoWebCache cache directory
    - JVM options ( JAVA_OPTS )

**Comment by randomorder** [comment]
Work in progress. Docker files available here:
- https://github.com/randomorder/docker-gs-base
- https://github.com/randomorder/docker-geoserver

**Comment by randomorder** [comment]
Images available no Docker hub:
https://hub.docker.com/r/geosolutionsit/gs-base/
https://hub.docker.com/r/geosolutionsit/geoserver/
