### ISSUE TITLE
Deploy Gray Earth with Shaded Relief, Hypsography, Ocean Bottom, and Drainages

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/eumetsat-EOWS#67]
[Gray Earth with Shaded Relief, Hypsography, Ocean Bottom, and Drainages](https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/raster/GRAY_HR_SR_OB_DR.zip)

To pre-process(tiles and overviews): https://docs.google.com/document/d/14CKHPORNm3OE7iLvzqqQgJ7OhVhxV5KAG1XTh70dFJU/edit

**Comment by simboss** [comment]
@Gnafu use @ElenaGallo for this

**Comment by Gnafu** [comment]
@ElenaGallo please update that google doc with a new section for the new gray background, with:
- link to the source file you processed
- gdal commands you used to process it

**Comment by ElenaGallo** [comment]
@Gnafu Hear the doc with link and GDAL comands for Gray Earth raster
[https://docs.google.com/document/d/18A1Eet530uh77qQ2o33165fgioPxDgCy82uF7pwAKEM/edit](https://docs.google.com/document/d/18A1Eet530uh77qQ2o33165fgioPxDgCy82uF7pwAKEM/edit)

**Comment by Gnafu** [comment]
Deployed on DEV
