### ISSUE TITLE
Externalize GeoServer Importer working directory

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/eumetsat-EOWS#71]
The importer is currently doing all its operations (unzip shapefiles) from inside the data dir.

Evaluate if externalizing the working folder will be helpful.

See https://osgeo-org.atlassian.net/browse/GEOS-8650

**Comment by simboss** [comment]
This should be implemented now.

Can you double check?

**Comment by Gnafu** [comment]
This task will become critical if the data_dir will be burned inside the docker images.
The distributed ingestion will work only if all instances have access to the uploaded files.

**Comment by Gnafu** [comment]
Waiting for Rosa to setup helm and git on the geosolutions account on the jump host so we can edit the Helm Chart and update the deploy with the external directory

**Comment by Gnafu** [comment]
New directory created on the NFS, pv and pvc created, helm chart updated.
Tested working on AWS DEV
