### ISSUE TITLE
WPS DownloadAnimation will stop after a maximum amount of frames

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/eumetsat-EOWS#81]
See http://fstaiga.eoss-cloud.it/project/admin-pathfinder_wms/issue/451.

**Comment by Gnafu** [comment]
Related to https://osgeo-org.atlassian.net/browse/GEOS-8715

**Comment by simboss** [comment]
@Gnafu can you prepare an isolated test case for this?

**Comment by Gnafu** [comment]
Request: https://demo.geo-solutions.it/share/eumetsat/download_animation_test.xml

**Comment by aaime** [comment]
Personal note. Almost there with the "fix", still need to:

- Write documentation for the WMS/WCS service limits
- Write tests and doc for the download animation limits
