### ISSUE TITLE
Ingestion of Global GHRSST

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/eumetsat-EOWS#84]
See related email discussion with Guillame.

**Comment by simboss** [comment]
@dromagnoli can you report the status here daniele?

**Comment by dromagnoli** [comment]
Attached zip containing NCMLs.
First one to do typeconversion.
Second one to do nc3 to nc4 rewriting.

[ncmls.zip](https://github.com/geosolutions-it/eumetsat-EOWS/files/1970263/ncmls.zip)

**Comment by dromagnoli** [comment]
ImageMosaic config files (datastore.properties, _auxiliary.xml and indexer.xml)
[mosaicConfig.zip](https://github.com/geosolutions-it/eumetsat-EOWS/files/1970325/mosaicConfig.zip)

Make sure to update datastore.properties with proper values and indexer.xml with proper path for auxiliary file.

**Comment by dromagnoli** [comment]
This JIRA could be related:
https://osgeo-org.atlassian.net/browse/GEOS-8632

**Comment by simboss** [comment]
is this one still open @dromagnoli ?
