### ISSUE TITLE
WCS protected layers cannot be loaded with QGIS

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/eumetsat-EOWS#87]
QGIS is not able to handle WCS urls with parameters.

See https://issues.qgis.org/issues/18929

**Comment by Gnafu** [comment]
See [GEOS-8741](https://osgeo-org.atlassian.net/browse/GEOS-8741)

Probably due to this : [Wcs10CapsTransformer.java#L485-L516](https://github.com/geoserver/geoserver/blob/76d043aeb79e6a3730a35b318cb7d6593cba1f79/src/wcs1_0/src/main/java/org/geoserver/wcs/response/Wcs10CapsTransformer.java#L485-L516)

**Comment by Gnafu** [comment]
There are 2 concurrent issues:
- GeoServer generates the wrong links in WCS 1.0.0
- QGIS overwrites the VERSION parameter to force it to be 1.0.0

**Comment by aaime** [comment]
Quoting from the QGIS documentation:

"QGIS has a native WCS provider and supports both version 1.0 and 1.1 (which are significantly different), but currently it prefers 1.0, because 1.1 has many issues (i.e., each server implements it in a different way with various particularities)."

**Comment by aaime** [comment]
@Gnafu the GeoServer ticket has been fixed. Not sure that anything can be done about QGIS honestly. Just these days people were discussing on the devel about dropping the existing WCS client and use GDAL directly instead.

So what to do about this ticket? Should I move it to "testing" state, or do you want to keep it open and active for the QGIS side? If so, what about splitting it into two tickets?
