### ISSUE TITLE
Test database improvements for vector data storage

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/eumetsat-EOWS#9]
Vector data has been loaded into a PostgrSQL database.
By default the SHP2PG tool creates "numeric" types that store up to 11 bytes per value (in our case)

Defining the correct data type we can reduce the stored data size and keep a reasonable precision.

**Comment by Gnafu** [comment]
In theory we can reduce the sample data by 28%, in practice the database indexes add some overhead so the actual reduction is by 15%

Here is the column type changes and the related size reduction:

| column | type before | type after | max used bytes before | max used bytes after |
| --- | --- | --- | --- | --- | 
| gid | integer | integer | 4 | 4 | 
| direction | numeric | smallint | 5 | 2 |
| longitude | numeric | numeric(13, 10) | 11 | 11 |
| latitude	 | numeric | numeric(13, 10) | 11 | 11 |
| wind_speed | numeric | numeric(5,2) | 11 | 4 |
| wind_direc | numeric | numeric(5,2) | 11 | 4 |
| backscatte | numeric | numeric(5,2) | 11 | 4 |
| lod | numeric | smallint | 5 | 2 |
| geom | geometry | geometry | 29 | 29 |

**Comment by simboss** [comment]
@Gnafu please, update this ticket

**Comment by Gnafu** [comment]
This ticket was in the review column because it is finished.
I copied the results in the comment to [a wiki page](https://github.com/geosolutions-it/eumetsat-EOWS/wiki/Database-reduction-results)
