### ISSUE TITLE
Backup everything

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/eumetsat-EOWS#93]
Setup backup jobs in the new infrastructure

**Comment by Gnafu** [comment]
Remember to backup the gwc_cache_dir *.xml files too

**Comment by randomorder** [comment]
Automated Datadir backup job has been planned and estimated. We're waiting for feedback from CGI. @Gnafu please consider backing up  gwc_cache_dir /*.xml as well

**Comment by randomorder** [comment]
still relevant? can we close this one?
